window:
  width: 1600
  height: 900
  fullscreen: false
  title: Engine
  vsync: false
system:
  system threads: 0
  enabled system:
    camera_system: true
    BehaviourSystem: true
    transform_system: true
    animation_system: true
    ParticleSystem: true
    HierarchySystem: true
  system configurations: ~
resource:
  resource threads: 0
  resource list: ~
  root directory: M:\gam300\bin
  enable globbing: false
logger:
  name: Engine
  output file: ""
  severity: 2
render:
  gamma: 2.20000005