// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Particle
// Generated on: 2025-11-29 15:28:25

// Includes for the header
#include "BasilEngine_Components_Particle_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Components.Particle
#include "Bindings/ManagedParticle.hpp"


void BasilEngine_Components_Particle_GLUE_GEN::Internal_Play(uint64_t handle)
{
	// Native Method: Name = Play
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::Play(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_Stop(uint64_t handle)
{
	// Native Method: Name = Stop
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::Stop(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_Reset(uint64_t handle)
{
	// Native Method: Name = Reset
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::Reset(handle);
}

mono_bool BasilEngine_Components_Particle_GLUE_GEN::Internal_IsPlaying(uint64_t handle)
{
	// Native Method: Name = IsPlaying
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::IsPlaying(handle);
}

mono_bool BasilEngine_Components_Particle_GLUE_GEN::Internal_IsAlive(uint64_t handle)
{
	// Native Method: Name = IsAlive
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::IsAlive(handle);
}

int32_t BasilEngine_Components_Particle_GLUE_GEN::Internal_GetActiveCount(uint64_t handle)
{
	// Native Method: Name = GetActiveCount
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetActiveCount(handle);
}

mono_bool BasilEngine_Components_Particle_GLUE_GEN::Internal_GetAutoPlay(uint64_t handle)
{
	// Native Method: Name = GetAutoPlay
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetAutoPlay(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetAutoPlay(uint64_t handle, mono_bool v)
{
	// Native Method: Name = SetAutoPlay
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetAutoPlay(handle, v);
}

int32_t BasilEngine_Components_Particle_GLUE_GEN::Internal_GetBlendMode(uint64_t handle)
{
	// Native Method: Name = GetBlendMode
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetBlendMode(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetBlendMode(uint64_t handle, int32_t v)
{
	// Native Method: Name = SetBlendMode
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetBlendMode(handle, v);
}

mono_bool BasilEngine_Components_Particle_GLUE_GEN::Internal_GetDepthWrite(uint64_t handle)
{
	// Native Method: Name = GetDepthWrite
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetDepthWrite(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetDepthWrite(uint64_t handle, mono_bool v)
{
	// Native Method: Name = SetDepthWrite
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetDepthWrite(handle, v);
}

uint32_t BasilEngine_Components_Particle_GLUE_GEN::Internal_GetRenderLayer(uint64_t handle)
{
	// Native Method: Name = GetRenderLayer
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetRenderLayer(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetRenderLayer(uint64_t handle, uint32_t v)
{
	// Native Method: Name = SetRenderLayer
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetRenderLayer(handle, v);
}

int32_t BasilEngine_Components_Particle_GLUE_GEN::Internal_GetEmissionType(uint64_t handle)
{
	// Native Method: Name = GetEmissionType
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetEmissionType(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetEmissionType(uint64_t handle, int32_t v)
{
	// Native Method: Name = SetEmissionType
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetEmissionType(handle, v);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetEmitterSizeX(uint64_t handle)
{
	// Native Method: Name = GetEmitterSizeX
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetEmitterSizeX(handle);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetEmitterSizeY(uint64_t handle)
{
	// Native Method: Name = GetEmitterSizeY
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetEmitterSizeY(handle);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetEmitterSizeZ(uint64_t handle)
{
	// Native Method: Name = GetEmitterSizeZ
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetEmitterSizeZ(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetEmitterSize(uint64_t handle, float x, float y, float z)
{
	// Native Method: Name = SetEmitterSize
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetEmitterSize(handle, x, y, z);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetSphereRadius(uint64_t handle)
{
	// Native Method: Name = GetSphereRadius
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetSphereRadius(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetSphereRadius(uint64_t handle, float r)
{
	// Native Method: Name = SetSphereRadius
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetSphereRadius(handle, r);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetEmissionRate(uint64_t handle)
{
	// Native Method: Name = GetEmissionRate
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetEmissionRate(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetEmissionRate(uint64_t handle, float v)
{
	// Native Method: Name = SetEmissionRate
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetEmissionRate(handle, v);
}

int32_t BasilEngine_Components_Particle_GLUE_GEN::Internal_GetMaxParticles(uint64_t handle)
{
	// Native Method: Name = GetMaxParticles
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetMaxParticles(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetMaxParticles(uint64_t handle, int32_t v)
{
	// Native Method: Name = SetMaxParticles
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetMaxParticles(handle, v);
}

mono_bool BasilEngine_Components_Particle_GLUE_GEN::Internal_GetLooping(uint64_t handle)
{
	// Native Method: Name = GetLooping
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetLooping(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetLooping(uint64_t handle, mono_bool v)
{
	// Native Method: Name = SetLooping
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetLooping(handle, v);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetDuration(uint64_t handle)
{
	// Native Method: Name = GetDuration
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetDuration(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetDuration(uint64_t handle, float v)
{
	// Native Method: Name = SetDuration
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetDuration(handle, v);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetMinLifetime(uint64_t handle)
{
	// Native Method: Name = GetMinLifetime
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetMinLifetime(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetMinLifetime(uint64_t handle, float v)
{
	// Native Method: Name = SetMinLifetime
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetMinLifetime(handle, v);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetMaxLifetime(uint64_t handle)
{
	// Native Method: Name = GetMaxLifetime
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetMaxLifetime(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetMaxLifetime(uint64_t handle, float v)
{
	// Native Method: Name = SetMaxLifetime
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetMaxLifetime(handle, v);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetStartColorR(uint64_t handle)
{
	// Native Method: Name = GetStartColorR
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetStartColorR(handle);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetStartColorG(uint64_t handle)
{
	// Native Method: Name = GetStartColorG
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetStartColorG(handle);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetStartColorB(uint64_t handle)
{
	// Native Method: Name = GetStartColorB
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetStartColorB(handle);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetStartColorA(uint64_t handle)
{
	// Native Method: Name = GetStartColorA
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetStartColorA(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetStartColor(uint64_t handle, float r, float g, float b, float a)
{
	// Native Method: Name = SetStartColor
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetStartColor(handle, r, g, b, a);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetEndColorR(uint64_t handle)
{
	// Native Method: Name = GetEndColorR
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetEndColorR(handle);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetEndColorG(uint64_t handle)
{
	// Native Method: Name = GetEndColorG
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetEndColorG(handle);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetEndColorB(uint64_t handle)
{
	// Native Method: Name = GetEndColorB
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetEndColorB(handle);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetEndColorA(uint64_t handle)
{
	// Native Method: Name = GetEndColorA
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetEndColorA(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetEndColor(uint64_t handle, float r, float g, float b, float a)
{
	// Native Method: Name = SetEndColor
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetEndColor(handle, r, g, b, a);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetStartSize(uint64_t handle)
{
	// Native Method: Name = GetStartSize
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetStartSize(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetStartSize(uint64_t handle, float v)
{
	// Native Method: Name = SetStartSize
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetStartSize(handle, v);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetEndSize(uint64_t handle)
{
	// Native Method: Name = GetEndSize
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetEndSize(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetEndSize(uint64_t handle, float v)
{
	// Native Method: Name = SetEndSize
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetEndSize(handle, v);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetStartRotation(uint64_t handle)
{
	// Native Method: Name = GetStartRotation
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetStartRotation(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetStartRotation(uint64_t handle, float v)
{
	// Native Method: Name = SetStartRotation
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetStartRotation(handle, v);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetRotationSpeed(uint64_t handle)
{
	// Native Method: Name = GetRotationSpeed
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetRotationSpeed(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetRotationSpeed(uint64_t handle, float v)
{
	// Native Method: Name = SetRotationSpeed
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetRotationSpeed(handle, v);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetStartVelX(uint64_t handle)
{
	// Native Method: Name = GetStartVelX
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetStartVelX(handle);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetStartVelY(uint64_t handle)
{
	// Native Method: Name = GetStartVelY
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetStartVelY(handle);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetStartVelZ(uint64_t handle)
{
	// Native Method: Name = GetStartVelZ
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetStartVelZ(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetStartVelocity(uint64_t handle, float x, float y, float z)
{
	// Native Method: Name = SetStartVelocity
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetStartVelocity(handle, x, y, z);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetVelocityRandomness(uint64_t handle)
{
	// Native Method: Name = GetVelocityRandomness
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetVelocityRandomness(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetVelocityRandomness(uint64_t handle, float v)
{
	// Native Method: Name = SetVelocityRandomness
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetVelocityRandomness(handle, v);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetAccelX(uint64_t handle)
{
	// Native Method: Name = GetAccelX
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetAccelX(handle);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetAccelY(uint64_t handle)
{
	// Native Method: Name = GetAccelY
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetAccelY(handle);
}

float BasilEngine_Components_Particle_GLUE_GEN::Internal_GetAccelZ(uint64_t handle)
{
	// Native Method: Name = GetAccelZ
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	return 	ManagedParticle::GetAccelZ(handle);
}

void BasilEngine_Components_Particle_GLUE_GEN::Internal_SetAcceleration(uint64_t handle, float x, float y, float z)
{
	// Native Method: Name = SetAcceleration
	// Static Accessor: Name = ManagedParticle, Type = DoubleColon
	ManagedParticle::SetAcceleration(handle, x, y, z);
}

void BasilEngine_Components_Particle_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Components.Particle
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_Play", (void*)Internal_Play);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_Stop", (void*)Internal_Stop);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_Reset", (void*)Internal_Reset);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_IsPlaying", (void*)Internal_IsPlaying);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_IsAlive", (void*)Internal_IsAlive);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetActiveCount", (void*)Internal_GetActiveCount);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetAutoPlay", (void*)Internal_GetAutoPlay);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetAutoPlay", (void*)Internal_SetAutoPlay);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetBlendMode", (void*)Internal_GetBlendMode);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetBlendMode", (void*)Internal_SetBlendMode);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetDepthWrite", (void*)Internal_GetDepthWrite);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetDepthWrite", (void*)Internal_SetDepthWrite);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetRenderLayer", (void*)Internal_GetRenderLayer);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetRenderLayer", (void*)Internal_SetRenderLayer);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetEmissionType", (void*)Internal_GetEmissionType);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetEmissionType", (void*)Internal_SetEmissionType);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetEmitterSizeX", (void*)Internal_GetEmitterSizeX);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetEmitterSizeY", (void*)Internal_GetEmitterSizeY);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetEmitterSizeZ", (void*)Internal_GetEmitterSizeZ);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetEmitterSize", (void*)Internal_SetEmitterSize);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetSphereRadius", (void*)Internal_GetSphereRadius);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetSphereRadius", (void*)Internal_SetSphereRadius);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetEmissionRate", (void*)Internal_GetEmissionRate);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetEmissionRate", (void*)Internal_SetEmissionRate);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetMaxParticles", (void*)Internal_GetMaxParticles);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetMaxParticles", (void*)Internal_SetMaxParticles);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetLooping", (void*)Internal_GetLooping);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetLooping", (void*)Internal_SetLooping);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetDuration", (void*)Internal_GetDuration);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetDuration", (void*)Internal_SetDuration);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetMinLifetime", (void*)Internal_GetMinLifetime);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetMinLifetime", (void*)Internal_SetMinLifetime);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetMaxLifetime", (void*)Internal_GetMaxLifetime);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetMaxLifetime", (void*)Internal_SetMaxLifetime);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetStartColorR", (void*)Internal_GetStartColorR);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetStartColorG", (void*)Internal_GetStartColorG);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetStartColorB", (void*)Internal_GetStartColorB);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetStartColorA", (void*)Internal_GetStartColorA);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetStartColor", (void*)Internal_SetStartColor);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetEndColorR", (void*)Internal_GetEndColorR);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetEndColorG", (void*)Internal_GetEndColorG);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetEndColorB", (void*)Internal_GetEndColorB);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetEndColorA", (void*)Internal_GetEndColorA);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetEndColor", (void*)Internal_SetEndColor);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetStartSize", (void*)Internal_GetStartSize);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetStartSize", (void*)Internal_SetStartSize);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetEndSize", (void*)Internal_GetEndSize);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetEndSize", (void*)Internal_SetEndSize);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetStartRotation", (void*)Internal_GetStartRotation);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetStartRotation", (void*)Internal_SetStartRotation);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetRotationSpeed", (void*)Internal_GetRotationSpeed);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetRotationSpeed", (void*)Internal_SetRotationSpeed);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetStartVelX", (void*)Internal_GetStartVelX);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetStartVelY", (void*)Internal_GetStartVelY);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetStartVelZ", (void*)Internal_GetStartVelZ);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetStartVelocity", (void*)Internal_SetStartVelocity);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetVelocityRandomness", (void*)Internal_GetVelocityRandomness);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetVelocityRandomness", (void*)Internal_SetVelocityRandomness);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetAccelX", (void*)Internal_GetAccelX);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetAccelY", (void*)Internal_GetAccelY);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_GetAccelZ", (void*)Internal_GetAccelZ);
	mono_add_internal_call("BasilEngine.Components.Particle::Internal_SetAcceleration", (void*)Internal_SetAcceleration);

}

