// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Camera
// Generated on: 2025-11-29 18:09:02

#ifndef BasilEngine_Components_Camera_GLUE_GEN_HPP
#define BasilEngine_Components_Camera_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Components.Camera
#include "Bindings/ManagedCamera.hpp"

// Object: BasilEngine_Components_Camera_GLUE_GEN
class BasilEngine_Components_Camera_GLUE_GEN {
// Methods for BasilEngine.Components.Camera
	static void Internal_SetType(uint64_t handle, int32_t type);
	static int32_t Internal_GetType(uint64_t handle);
	static void Internal_SetFOV(uint64_t handle, float fov);
	static float Internal_GetFOV(uint64_t handle);
	static void Internal_SetAspectRatio(uint64_t handle, float ratio);
	static float Internal_GetAspectRatio(uint64_t handle);
	static void Internal_SetNearPlane(uint64_t handle, float near);
	static void Internal_SetFarPlane(uint64_t handle, float far);
	static float Internal_GetNearPlane(uint64_t handle);
	static float Internal_GetFarPlane(uint64_t handle);
	static void Internal_ScreenToWorldPoint(uint64_t handle, float x, float y, float depth, float* wx, float* wy, float* wz);
	static void Internal_ScreenPointToRay(uint64_t handle, float x, float y, float _unusedDepth, float* ox, float* oy, float* oz, float* dx, float* dy, float* dz);

	// Bindings for BasilEngine.Components.Camera
	public:
		static void Bind();

};

#endif // BasilEngine_Components_Camera_GLUE_GEN_HPP

