// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.SceneManagement.Scene
// Generated on: 2026-02-08 17:03:57

// Includes for the header
#include "BasilEngine_SceneManagement_Scene_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.SceneManagement.Scene
#include "Bindings/ManagedScene.hpp"


void BasilEngine_SceneManagement_Scene_GLUE_GEN::LoadSceneByName(MonoString* sceneName)
{
	// Native Method: Name = LoadSceneName
	// Static Accessor: Name = ManagedScene, Type = DoubleColon
	ManagedScene::LoadSceneName(sceneName);
}

void BasilEngine_SceneManagement_Scene_GLUE_GEN::LoadSceneByIndex(int32_t index)
{
	// Native Method: Name = LoadSceneIndex
	// Static Accessor: Name = ManagedScene, Type = DoubleColon
	ManagedScene::LoadSceneIndex(index);
}

void BasilEngine_SceneManagement_Scene_GLUE_GEN::ExitApplication()
{
	// Native Method: Name = ExitApplication
	// Static Accessor: Name = ManagedScene, Type = DoubleColon
	ManagedScene::ExitApplication();
}

void BasilEngine_SceneManagement_Scene_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.SceneManagement.Scene
	mono_add_internal_call("BasilEngine.SceneManagement.Scene::LoadSceneByName", (void*)LoadSceneByName);
	mono_add_internal_call("BasilEngine.SceneManagement.Scene::LoadSceneByIndex", (void*)LoadSceneByIndex);
	mono_add_internal_call("BasilEngine.SceneManagement.Scene::ExitApplication", (void*)ExitApplication);

}

