// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Light
// Generated on: 2025-11-13 21:03:13

#ifndef BasilEngine_Components_Light_GLUE_GEN_HPP
#define BasilEngine_Components_Light_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Components.Light
#include "Bindings/ManagedLight.hpp"

// Object: BasilEngine_Components_Light_GLUE_GEN
class BasilEngine_Components_Light_GLUE_GEN {
// Methods for BasilEngine.Components.Light
	static void Internal_SetType(uint64_t handle, int32_t type);
	static int32_t Internal_GetType(uint64_t handle);
	static mono_bool Internal_GetEnabled(uint64_t handle);
	static void Internal_SetEnabled(uint64_t handle, mono_bool v);
	static float Internal_GetColorR(uint64_t handle);
	static float Internal_GetColorG(uint64_t handle);
	static float Internal_GetColorB(uint64_t handle);
	static void Internal_SetColor(uint64_t handle, float r, float g, float b);
	static void Internal_SetColorR(uint64_t handle, float r);
	static void Internal_SetColorG(uint64_t handle, float g);
	static void Internal_SetColorB(uint64_t handle, float b);
	static float Internal_GetIntensity(uint64_t handle);
	static void Internal_SetIntensity(uint64_t handle, float v);
	static float Internal_GetDirectionX(uint64_t handle);
	static float Internal_GetDirectionY(uint64_t handle);
	static float Internal_GetDirectionZ(uint64_t handle);
	static void Internal_SetDirection(uint64_t handle, float x, float y, float z);
	static float Internal_GetRange(uint64_t handle);
	static void Internal_SetRange(uint64_t handle, float v);
	static float Internal_GetInnerConeDeg(uint64_t handle);
	static float Internal_GetOuterConeDeg(uint64_t handle);
	static void Internal_SetCones(uint64_t handle, float innerDeg, float outerDeg);

	// Bindings for BasilEngine.Components.Light
	public:
		static void Bind();

};

#endif // BasilEngine_Components_Light_GLUE_GEN_HPP

