// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Debug.Logger
// Generated on: 2026-03-20 19:46:59

#ifndef BasilEngine_Debug_Logger_GLUE_GEN_HPP
#define BasilEngine_Debug_Logger_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Debug.Logger
#include "Bindings/MANAGED_CONSOLE.hpp"

// Object: BasilEngine_Debug_Logger_GLUE_GEN
class BasilEngine_Debug_Logger_GLUE_GEN {
// Methods for BasilEngine.Debug.Logger
	static void internal_Log(MonoString* message);
	static void internal_Warn(MonoString* message);
	static void internal_Error(MonoString* message);

	// Bindings for BasilEngine.Debug.Logger
	public:
		static void Bind();

};

#endif // BasilEngine_Debug_Logger_GLUE_GEN_HPP

