// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Button
// Generated on: 2026-03-01 03:04:16

// Includes for the header
#include "BasilEngine_Components_Button_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Components.Button
#include "Bindings/ManagedButton.hpp"


mono_bool BasilEngine_Components_Button_GLUE_GEN::GetHoveredInternal(uint64_t handle)
{
	// Native Method: Name = GetHovered
	// Static Accessor: Name = ManagedButton, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedButton::GetHovered(handle));
}

mono_bool BasilEngine_Components_Button_GLUE_GEN::GetPressedInternal(uint64_t handle)
{
	// Native Method: Name = GetPressed
	// Static Accessor: Name = ManagedButton, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedButton::GetPressed(handle));
}

mono_bool BasilEngine_Components_Button_GLUE_GEN::GetClickedInternal(uint64_t handle)
{
	// Native Method: Name = GetClicked
	// Static Accessor: Name = ManagedButton, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedButton::GetClicked(handle));
}

void BasilEngine_Components_Button_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Components.Button
	mono_add_internal_call("BasilEngine.Components.Button::GetHoveredInternal", (void*)GetHoveredInternal);
	mono_add_internal_call("BasilEngine.Components.Button::GetPressedInternal", (void*)GetPressedInternal);
	mono_add_internal_call("BasilEngine.Components.Button::GetClickedInternal", (void*)GetClickedInternal);

}

