// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Ray
// Generated on: 2025-11-25 07:27:31

#ifndef BasilEngine_Ray_GLUE_GEN_HPP
#define BasilEngine_Ray_GLUE_GEN_HPP

// Object: BasilEngine_Ray_GLUE_GEN
struct BasilEngine_Ray_GLUE_GEN {
	// Bindings for BasilEngine.Ray
	public:
		static void Bind();

};

#endif // BasilEngine_Ray_GLUE_GEN_HPP

