// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Physics
// Generated on: 2026-02-01 12:57:28

#ifndef BasilEngine_Physics_GLUE_GEN_HPP
#define BasilEngine_Physics_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Physics
#include "Bindings/ManagedPhysics.hpp"

// Object: BasilEngine_Physics_GLUE_GEN
class BasilEngine_Physics_GLUE_GEN {
// Methods for BasilEngine.Physics
	static mono_bool Internal_Raycast(float ox, float oy, float oz, float dx, float dy, float dz, float maxDistance, mono_bool ignoreTriggers, uint64_t* entity, float* px, float* py, float* pz, float* nx, float* ny, float* nz, float* distance, uint8_t* isTrigger);

	// Bindings for BasilEngine.Physics
	public:
		static void Bind();

};

#endif // BasilEngine_Physics_GLUE_GEN_HPP

