// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.MeshRenderer
// Generated on: 2026-02-07 11:19:09

// Includes for the header
#include "BasilEngine_Components_MeshRenderer_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Components.MeshRenderer
#include "Bindings/ManagedMeshRenderer.hpp"


void BasilEngine_Components_MeshRenderer_GLUE_GEN::Internal_GetAlbedoColor(uint64_t handle, float* r, float* g, float* b)
{
	// Native Method: Name = GetAlbedoColor
	// Static Accessor: Name = ManagedMeshRenderer, Type = DoubleColon
	ManagedMeshRenderer::GetAlbedoColor(handle, r, g, b);
}

void BasilEngine_Components_MeshRenderer_GLUE_GEN::Internal_SetAlbedoColor(uint64_t handle, float r, float g, float b)
{
	// Native Method: Name = SetAlbedoColor
	// Static Accessor: Name = ManagedMeshRenderer, Type = DoubleColon
	ManagedMeshRenderer::SetAlbedoColor(handle, r, g, b);
}

float BasilEngine_Components_MeshRenderer_GLUE_GEN::Internal_GetMetallic(uint64_t handle)
{
	// Native Method: Name = GetMetallic
	// Static Accessor: Name = ManagedMeshRenderer, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedMeshRenderer::GetMetallic(handle));
}

void BasilEngine_Components_MeshRenderer_GLUE_GEN::Internal_SetMetallic(uint64_t handle, float value)
{
	// Native Method: Name = SetMetallic
	// Static Accessor: Name = ManagedMeshRenderer, Type = DoubleColon
	ManagedMeshRenderer::SetMetallic(handle, value);
}

float BasilEngine_Components_MeshRenderer_GLUE_GEN::Internal_GetRoughness(uint64_t handle)
{
	// Native Method: Name = GetRoughness
	// Static Accessor: Name = ManagedMeshRenderer, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedMeshRenderer::GetRoughness(handle));
}

void BasilEngine_Components_MeshRenderer_GLUE_GEN::Internal_SetRoughness(uint64_t handle, float value)
{
	// Native Method: Name = SetRoughness
	// Static Accessor: Name = ManagedMeshRenderer, Type = DoubleColon
	ManagedMeshRenderer::SetRoughness(handle, value);
}

void BasilEngine_Components_MeshRenderer_GLUE_GEN::Internal_SetFloatOverride(uint64_t handle, MonoString* propertyName, float value)
{
	// Native Method: Name = SetFloatOverride
	// Static Accessor: Name = ManagedMeshRenderer, Type = DoubleColon
	ManagedMeshRenderer::SetFloatOverride(handle, propertyName, value);
}

void BasilEngine_Components_MeshRenderer_GLUE_GEN::Internal_SetVec3Override(uint64_t handle, MonoString* propertyName, float x, float y, float z)
{
	// Native Method: Name = SetVec3Override
	// Static Accessor: Name = ManagedMeshRenderer, Type = DoubleColon
	ManagedMeshRenderer::SetVec3Override(handle, propertyName, x, y, z);
}

void BasilEngine_Components_MeshRenderer_GLUE_GEN::Internal_SetVec4Override(uint64_t handle, MonoString* propertyName, float x, float y, float z, float w)
{
	// Native Method: Name = SetVec4Override
	// Static Accessor: Name = ManagedMeshRenderer, Type = DoubleColon
	ManagedMeshRenderer::SetVec4Override(handle, propertyName, x, y, z, w);
}

mono_bool BasilEngine_Components_MeshRenderer_GLUE_GEN::Internal_HasOverride(uint64_t handle, MonoString* propertyName)
{
	// Native Method: Name = HasOverride
	// Static Accessor: Name = ManagedMeshRenderer, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedMeshRenderer::HasOverride(handle, propertyName));
}

void BasilEngine_Components_MeshRenderer_GLUE_GEN::Internal_ClearOverride(uint64_t handle, MonoString* propertyName)
{
	// Native Method: Name = ClearOverride
	// Static Accessor: Name = ManagedMeshRenderer, Type = DoubleColon
	ManagedMeshRenderer::ClearOverride(handle, propertyName);
}

void BasilEngine_Components_MeshRenderer_GLUE_GEN::Internal_ClearAllOverrides(uint64_t handle)
{
	// Native Method: Name = ClearAllOverrides
	// Static Accessor: Name = ManagedMeshRenderer, Type = DoubleColon
	ManagedMeshRenderer::ClearAllOverrides(handle);
}

mono_bool BasilEngine_Components_MeshRenderer_GLUE_GEN::Internal_GetVisible(uint64_t handle)
{
	// Native Method: Name = GetVisible
	// Static Accessor: Name = ManagedMeshRenderer, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedMeshRenderer::GetVisible(handle));
}

void BasilEngine_Components_MeshRenderer_GLUE_GEN::Internal_SetVisible(uint64_t handle, mono_bool visible)
{
	// Native Method: Name = SetVisible
	// Static Accessor: Name = ManagedMeshRenderer, Type = DoubleColon
	ManagedMeshRenderer::SetVisible(handle, visible);
}

void BasilEngine_Components_MeshRenderer_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Components.MeshRenderer
	mono_add_internal_call("BasilEngine.Components.MeshRenderer::Internal_GetAlbedoColor", (void*)Internal_GetAlbedoColor);
	mono_add_internal_call("BasilEngine.Components.MeshRenderer::Internal_SetAlbedoColor", (void*)Internal_SetAlbedoColor);
	mono_add_internal_call("BasilEngine.Components.MeshRenderer::Internal_GetMetallic", (void*)Internal_GetMetallic);
	mono_add_internal_call("BasilEngine.Components.MeshRenderer::Internal_SetMetallic", (void*)Internal_SetMetallic);
	mono_add_internal_call("BasilEngine.Components.MeshRenderer::Internal_GetRoughness", (void*)Internal_GetRoughness);
	mono_add_internal_call("BasilEngine.Components.MeshRenderer::Internal_SetRoughness", (void*)Internal_SetRoughness);
	mono_add_internal_call("BasilEngine.Components.MeshRenderer::Internal_SetFloatOverride", (void*)Internal_SetFloatOverride);
	mono_add_internal_call("BasilEngine.Components.MeshRenderer::Internal_SetVec3Override", (void*)Internal_SetVec3Override);
	mono_add_internal_call("BasilEngine.Components.MeshRenderer::Internal_SetVec4Override", (void*)Internal_SetVec4Override);
	mono_add_internal_call("BasilEngine.Components.MeshRenderer::Internal_HasOverride", (void*)Internal_HasOverride);
	mono_add_internal_call("BasilEngine.Components.MeshRenderer::Internal_ClearOverride", (void*)Internal_ClearOverride);
	mono_add_internal_call("BasilEngine.Components.MeshRenderer::Internal_ClearAllOverrides", (void*)Internal_ClearAllOverrides);
	mono_add_internal_call("BasilEngine.Components.MeshRenderer::Internal_GetVisible", (void*)Internal_GetVisible);
	mono_add_internal_call("BasilEngine.Components.MeshRenderer::Internal_SetVisible", (void*)Internal_SetVisible);

}

