// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Engine
// Generated on: 2026-04-01 04:21:55

#ifndef BasilEngine_Engine_GLUE_GEN_HPP
#define BasilEngine_Engine_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Engine
#include "Bindings/ManagedEngine.hpp"

// Object: BasilEngine_Engine_GLUE_GEN
class BasilEngine_Engine_GLUE_GEN {
// Methods for BasilEngine.Engine
	static float GetGammaInternal();
	static void SetGammaInternal(float gamma);

	// Bindings for BasilEngine.Engine
	public:
		static void Bind();

};

#endif // BasilEngine_Engine_GLUE_GEN_HPP

