// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.WorldUI
// Generated on: 2026-03-09 17:06:07

// Includes for the header
#include "BasilEngine_Components_WorldUI_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Components.WorldUI
#include "Bindings/ManagedWorldUI.hpp"


void BasilEngine_Components_WorldUI_GLUE_GEN::SetScaleInternal(uint64_t handle, float x, float y)
{
	// Native Method: Name = SetScale
	// Static Accessor: Name = ManagedWorldUI, Type = DoubleColon
	ManagedWorldUI::SetScale(handle, x, y);
}

void BasilEngine_Components_WorldUI_GLUE_GEN::GetScaleInternal(uint64_t handle, float* x, float* y)
{
	// Native Method: Name = GetScale
	// Static Accessor: Name = ManagedWorldUI, Type = DoubleColon
	ManagedWorldUI::GetScale(handle, x, y);
}

void BasilEngine_Components_WorldUI_GLUE_GEN::SetVisibleInternal(uint64_t handle, mono_bool visibility)
{
	// Native Method: Name = SetVisibility
	// Static Accessor: Name = ManagedWorldUI, Type = DoubleColon
	ManagedWorldUI::SetVisibility(handle, visibility);
}

mono_bool BasilEngine_Components_WorldUI_GLUE_GEN::GetVisibleInternal(uint64_t handle)
{
	// Native Method: Name = GetVisibility
	// Static Accessor: Name = ManagedWorldUI, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedWorldUI::GetVisibility(handle));
}

void BasilEngine_Components_WorldUI_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Components.WorldUI
	mono_add_internal_call("BasilEngine.Components.WorldUI::SetScaleInternal", (void*)SetScaleInternal);
	mono_add_internal_call("BasilEngine.Components.WorldUI::GetScaleInternal", (void*)GetScaleInternal);
	mono_add_internal_call("BasilEngine.Components.WorldUI::SetVisibleInternal", (void*)SetVisibleInternal);
	mono_add_internal_call("BasilEngine.Components.WorldUI::GetVisibleInternal", (void*)GetVisibleInternal);

}

