// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.HudComponent
// Generated on: 2026-03-20 17:02:02

// Includes for the header
#include "BasilEngine_Components_HudComponent_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Components.HudComponent
#include "Bindings/ManagedHudComponent.hpp"


void BasilEngine_Components_HudComponent_GLUE_GEN::SetVisibleInternal(uint64_t handle, mono_bool visibility)
{
	// Native Method: Name = SetVisibility
	// Static Accessor: Name = ManagedHudComponent, Type = DoubleColon
	ManagedHudComponent::SetVisibility(handle, visibility);
}

mono_bool BasilEngine_Components_HudComponent_GLUE_GEN::GetVisibleInternal(uint64_t handle)
{
	// Native Method: Name = GetVisibility
	// Static Accessor: Name = ManagedHudComponent, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedHudComponent::GetVisibility(handle));
}

void BasilEngine_Components_HudComponent_GLUE_GEN::SetPositionInternal(uint64_t handle, float x, float y)
{
	// Native Method: Name = SetPosition
	// Static Accessor: Name = ManagedHudComponent, Type = DoubleColon
	ManagedHudComponent::SetPosition(handle, x, y);
}

void BasilEngine_Components_HudComponent_GLUE_GEN::GetPositionInternal(uint64_t handle, float* x, float* y)
{
	// Native Method: Name = GetPosition
	// Static Accessor: Name = ManagedHudComponent, Type = DoubleColon
	ManagedHudComponent::GetPosition(handle, x, y);
}

void BasilEngine_Components_HudComponent_GLUE_GEN::GetSizeInternal(uint64_t handle, float* width, float* height)
{
	// Native Method: Name = GetSize
	// Static Accessor: Name = ManagedHudComponent, Type = DoubleColon
	ManagedHudComponent::GetSize(handle, width, height);
}

void BasilEngine_Components_HudComponent_GLUE_GEN::SetSizeInternal(uint64_t handle, float width, float height)
{
	// Native Method: Name = SetSize
	// Static Accessor: Name = ManagedHudComponent, Type = DoubleColon
	ManagedHudComponent::SetSize(handle, width, height);
}

void BasilEngine_Components_HudComponent_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Components.HudComponent
	mono_add_internal_call("BasilEngine.Components.HudComponent::SetVisibleInternal", (void*)SetVisibleInternal);
	mono_add_internal_call("BasilEngine.Components.HudComponent::GetVisibleInternal", (void*)GetVisibleInternal);
	mono_add_internal_call("BasilEngine.Components.HudComponent::SetPositionInternal", (void*)SetPositionInternal);
	mono_add_internal_call("BasilEngine.Components.HudComponent::GetPositionInternal", (void*)GetPositionInternal);
	mono_add_internal_call("BasilEngine.Components.HudComponent::GetSizeInternal", (void*)GetSizeInternal);
	mono_add_internal_call("BasilEngine.Components.HudComponent::SetSizeInternal", (void*)SetSizeInternal);

}

