// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Ray
// Generated on: 2025-11-25 13:06:59

// Includes for the header
#include "BasilEngine_Ray_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Ray


void BasilEngine_Ray_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Ray

}

