// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Button
// Generated on: 2026-03-30 01:48:51

#ifndef BasilEngine_Components_Button_GLUE_GEN_HPP
#define BasilEngine_Components_Button_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Components.Button
#include "Bindings/ManagedButton.hpp"

// Object: BasilEngine_Components_Button_GLUE_GEN
class BasilEngine_Components_Button_GLUE_GEN {
// Methods for BasilEngine.Components.Button
	static mono_bool GetHoveredInternal(uint64_t handle);
	static mono_bool GetPressedInternal(uint64_t handle);
	static mono_bool GetClickedInternal(uint64_t handle);
	static mono_bool GetDisabledInternal(uint64_t handle);
	static void SetDisabledInternal(uint64_t handle, mono_bool disabled);

	// Bindings for BasilEngine.Components.Button
	public:
		static void Bind();

};

#endif // BasilEngine_Components_Button_GLUE_GEN_HPP

