// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Component
// Generated on: 2025-11-08 19:18:01

// Includes for the header
#include "BasilEngine_Components_Component_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Components.Component
#include "Bindings/ManagedComponents.hpp"


uint32_t BasilEngine_Components_Component_GLUE_GEN::Internal_RegisterComponent(MonoString* name)
{
	// Native Method: Name = ManagedRegisterComponent
	// Static Accessor: Name = ManagedComponents, Type = DoubleColon
	return 	ManagedComponents::ManagedRegisterComponent(name);
}

mono_bool BasilEngine_Components_Component_GLUE_GEN::Internal_HasComponent(uint64_t handle, uint32_t typeHandle)
{
	// Native Method: Name = HasComponent
	// Static Accessor: Name = ManagedComponents, Type = DoubleColon
	return 	ManagedComponents::HasComponent(handle, typeHandle);
}

void BasilEngine_Components_Component_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Components.Component
	mono_add_internal_call("BasilEngine.Components.Component::Internal_RegisterComponent", (void*)Internal_RegisterComponent);
	mono_add_internal_call("BasilEngine.Components.Component::Internal_HasComponent", (void*)Internal_HasComponent);

}

