// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.GameObject
// Generated on: 2026-03-06 15:18:29

#ifndef BasilEngine_GameObject_GLUE_GEN_HPP
#define BasilEngine_GameObject_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.GameObject
#include "Bindings/ManagedGameObjects.hpp"

// Object: BasilEngine_GameObject_GLUE_GEN
class BasilEngine_GameObject_GLUE_GEN {
// Methods for BasilEngine.GameObject
	static uint64_t internal_Find(MonoString* name);
	static void DeleteGameObjectInternal(uint64_t handle);
	static void SetVisibleInternal(uint64_t handle, mono_bool visible);
	static mono_bool GetVisibleInternal(uint64_t handle);

	// Bindings for BasilEngine.GameObject
	public:
		static void Bind();

};

#endif // BasilEngine_GameObject_GLUE_GEN_HPP

