// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Video
// Generated on: 2026-02-07 23:57:45

// Includes for the header
#include "BasilEngine_Components_Video_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Components.Video
#include "Bindings/ManagedVideo.hpp"


mono_bool BasilEngine_Components_Video_GLUE_GEN::GetIsPlayingInternal(uint64_t handle)
{
	// Native Method: Name = GetIsPlaying
	// Static Accessor: Name = ManagedVideo, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedVideo::GetIsPlaying(handle));
}

void BasilEngine_Components_Video_GLUE_GEN::SetPlayingInternal(uint64_t handle, mono_bool value)
{
	// Native Method: Name = SetPlaying
	// Static Accessor: Name = ManagedVideo, Type = DoubleColon
	ManagedVideo::SetPlaying(handle, value);
}

void BasilEngine_Components_Video_GLUE_GEN::SetLoopInternal(uint64_t handle, mono_bool value)
{
	// Native Method: Name = SetIsLooping
	// Static Accessor: Name = ManagedVideo, Type = DoubleColon
	ManagedVideo::SetIsLooping(handle, value);
}

void BasilEngine_Components_Video_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Components.Video
	mono_add_internal_call("BasilEngine.Components.Video::GetIsPlayingInternal", (void*)GetIsPlayingInternal);
	mono_add_internal_call("BasilEngine.Components.Video::SetPlayingInternal", (void*)SetPlayingInternal);
	mono_add_internal_call("BasilEngine.Components.Video::SetLoopInternal", (void*)SetLoopInternal);

}

