// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Engine
// Generated on: 2026-03-31 06:03:46

// Includes for the header
#include "BasilEngine_Engine_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Engine
#include "Bindings/ManagedEngine.hpp"


float BasilEngine_Engine_GLUE_GEN::GetGammaInternal()
{
	// Native Method: Name = GetGamma
	// Static Accessor: Name = ManagedEngine, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedEngine::GetGamma());
}

void BasilEngine_Engine_GLUE_GEN::SetGammaInternal(float gamma)
{
	// Native Method: Name = SetGamma
	// Static Accessor: Name = ManagedEngine, Type = DoubleColon
	ManagedEngine::SetGamma(gamma);
}

void BasilEngine_Engine_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Engine
	mono_add_internal_call("BasilEngine.Engine::GetGammaInternal", (void*)GetGammaInternal);
	mono_add_internal_call("BasilEngine.Engine::SetGammaInternal", (void*)SetGammaInternal);

}

