// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Audio
// Generated on: 2025-11-16 12:49:30

#ifndef BasilEngine_Components_Audio_GLUE_GEN_HPP
#define BasilEngine_Components_Audio_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Components.Audio
#include "Bindings/ManagedAudio.hpp"

// Object: BasilEngine_Components_Audio_GLUE_GEN
class BasilEngine_Components_Audio_GLUE_GEN {
// Methods for BasilEngine.Components.Audio
	static void setVolume(uint64_t handle, float volume);
	static float getVolume(uint64_t handle);
	static void SetIsLooping(uint64_t handle, mono_bool isLooping);
	static mono_bool GetIsLooping(uint64_t handle);
	static void InternalPlay(uint64_t handle);
	static void InternalPause(uint64_t handle);
	static void InternalStop(uint64_t handle);

	// Bindings for BasilEngine.Components.Audio
	public:
		static void Bind();

};

#endif // BasilEngine_Components_Audio_GLUE_GEN_HPP

