// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Input
// Generated on: 2026-03-12 21:37:11

#ifndef BasilEngine_Input_GLUE_GEN_HPP
#define BasilEngine_Input_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Input
#include "Bindings/ManagedInput.hpp"

// Object: BasilEngine_Input_GLUE_GEN
class BasilEngine_Input_GLUE_GEN {
// Methods for BasilEngine.Input
	static mono_bool GetKeyInternal(int32_t key);
	static mono_bool GetKeyOnce(int32_t key);
	static void GetMouseScreenPosInternal(float* x, float* y);
	static void SetCursorLockedInternal(mono_bool locked);

	// Bindings for BasilEngine.Input
	public:
		static void Bind();

};

#endif // BasilEngine_Input_GLUE_GEN_HPP

