// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Transform
// Generated on: 2025-11-30 04:05:49

#ifndef BasilEngine_Components_Transform_GLUE_GEN_HPP
#define BasilEngine_Components_Transform_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Components.Transform
#include "Bindings/ManagedTransform.hpp"

// Object: BasilEngine_Components_Transform_GLUE_GEN
class BasilEngine_Components_Transform_GLUE_GEN {
// Methods for BasilEngine.Components.Transform
	static void SetPosition(uint64_t handle, float x, float y, float z);
	static void GetPosition(uint64_t handle, float* x, float* y, float* z);
	static void SetRotationInternal(uint64_t handle, float x, float y, float z);
	static void GetRotationInternal(uint64_t handle, float* x, float* y, float* z);
	static void SetScaleInternal(uint64_t handle, float x, float y, float z);
	static void GetScaleInternal(uint64_t handle, float* x, float* y, float* z);
	static void GetForwardInternal(uint64_t handle, float* x, float* y, float* z);
	static void GetRightInternal(uint64_t handle, float* x, float* y, float* z);
	static void GetUpInternal(uint64_t handle, float* x, float* y, float* z);

	// Bindings for BasilEngine.Components.Transform
	public:
		static void Bind();

};

#endif // BasilEngine_Components_Transform_GLUE_GEN_HPP

