// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Screen
// Generated on: 2026-02-07 14:58:32

// Includes for the header
#include "BasilEngine_Screen_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Screen
#include "Bindings/ManagedScreen.hpp"


int32_t BasilEngine_Screen_GLUE_GEN::Internal_GetWidth()
{
	// Native Method: Name = GetWidth
	// Static Accessor: Name = ManagedScreen, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedScreen::GetWidth());
}

int32_t BasilEngine_Screen_GLUE_GEN::Internal_GetHeight()
{
	// Native Method: Name = GetHeight
	// Static Accessor: Name = ManagedScreen, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedScreen::GetHeight());
}

void BasilEngine_Screen_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Screen
	mono_add_internal_call("BasilEngine.Screen::Internal_GetWidth", (void*)Internal_GetWidth);
	mono_add_internal_call("BasilEngine.Screen::Internal_GetHeight", (void*)Internal_GetHeight);

}

