// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Screen
// Generated on: 2025-11-30 14:10:53

#ifndef BasilEngine_Screen_GLUE_GEN_HPP
#define BasilEngine_Screen_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Screen
#include "Bindings/ManagedScreen.hpp"

// Object: BasilEngine_Screen_GLUE_GEN
class BasilEngine_Screen_GLUE_GEN {
// Methods for BasilEngine.Screen
	static int32_t Internal_GetWidth();
	static int32_t Internal_GetHeight();

	// Bindings for BasilEngine.Screen
	public:
		static void Bind();

};

#endif // BasilEngine_Screen_GLUE_GEN_HPP

