// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Particle
// Generated on: 2026-02-07 14:58:32

#ifndef BasilEngine_Components_Particle_GLUE_GEN_HPP
#define BasilEngine_Components_Particle_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Components.Particle
#include "Bindings/ManagedParticle.hpp"

// Object: BasilEngine_Components_Particle_GLUE_GEN
class BasilEngine_Components_Particle_GLUE_GEN {
// Methods for BasilEngine.Components.Particle
	static void Internal_Play(uint64_t handle);
	static void Internal_Stop(uint64_t handle);
	static void Internal_Reset(uint64_t handle);
	static mono_bool Internal_IsPlaying(uint64_t handle);
	static mono_bool Internal_IsAlive(uint64_t handle);
	static int32_t Internal_GetActiveCount(uint64_t handle);
	static mono_bool Internal_GetAutoPlay(uint64_t handle);
	static void Internal_SetAutoPlay(uint64_t handle, mono_bool v);
	static int32_t Internal_GetBlendMode(uint64_t handle);
	static void Internal_SetBlendMode(uint64_t handle, int32_t v);
	static mono_bool Internal_GetDepthWrite(uint64_t handle);
	static void Internal_SetDepthWrite(uint64_t handle, mono_bool v);
	static uint32_t Internal_GetRenderLayer(uint64_t handle);
	static void Internal_SetRenderLayer(uint64_t handle, uint32_t v);
	static int32_t Internal_GetEmissionType(uint64_t handle);
	static void Internal_SetEmissionType(uint64_t handle, int32_t v);
	static float Internal_GetEmitterSizeX(uint64_t handle);
	static float Internal_GetEmitterSizeY(uint64_t handle);
	static float Internal_GetEmitterSizeZ(uint64_t handle);
	static void Internal_SetEmitterSize(uint64_t handle, float x, float y, float z);
	static float Internal_GetSphereRadius(uint64_t handle);
	static void Internal_SetSphereRadius(uint64_t handle, float r);
	static float Internal_GetEmissionRate(uint64_t handle);
	static void Internal_SetEmissionRate(uint64_t handle, float v);
	static int32_t Internal_GetMaxParticles(uint64_t handle);
	static void Internal_SetMaxParticles(uint64_t handle, int32_t v);
	static mono_bool Internal_GetLooping(uint64_t handle);
	static void Internal_SetLooping(uint64_t handle, mono_bool v);
	static float Internal_GetDuration(uint64_t handle);
	static void Internal_SetDuration(uint64_t handle, float v);
	static float Internal_GetMinLifetime(uint64_t handle);
	static void Internal_SetMinLifetime(uint64_t handle, float v);
	static float Internal_GetMaxLifetime(uint64_t handle);
	static void Internal_SetMaxLifetime(uint64_t handle, float v);
	static float Internal_GetStartColorR(uint64_t handle);
	static float Internal_GetStartColorG(uint64_t handle);
	static float Internal_GetStartColorB(uint64_t handle);
	static float Internal_GetStartColorA(uint64_t handle);
	static void Internal_SetStartColor(uint64_t handle, float r, float g, float b, float a);
	static float Internal_GetEndColorR(uint64_t handle);
	static float Internal_GetEndColorG(uint64_t handle);
	static float Internal_GetEndColorB(uint64_t handle);
	static float Internal_GetEndColorA(uint64_t handle);
	static void Internal_SetEndColor(uint64_t handle, float r, float g, float b, float a);
	static float Internal_GetStartSize(uint64_t handle);
	static void Internal_SetStartSize(uint64_t handle, float v);
	static float Internal_GetEndSize(uint64_t handle);
	static void Internal_SetEndSize(uint64_t handle, float v);
	static float Internal_GetStartRotation(uint64_t handle);
	static void Internal_SetStartRotation(uint64_t handle, float v);
	static float Internal_GetRotationSpeed(uint64_t handle);
	static void Internal_SetRotationSpeed(uint64_t handle, float v);
	static float Internal_GetStartVelX(uint64_t handle);
	static float Internal_GetStartVelY(uint64_t handle);
	static float Internal_GetStartVelZ(uint64_t handle);
	static void Internal_SetStartVelocity(uint64_t handle, float x, float y, float z);
	static float Internal_GetVelocityRandomness(uint64_t handle);
	static void Internal_SetVelocityRandomness(uint64_t handle, float v);
	static float Internal_GetAccelX(uint64_t handle);
	static float Internal_GetAccelY(uint64_t handle);
	static float Internal_GetAccelZ(uint64_t handle);
	static void Internal_SetAcceleration(uint64_t handle, float x, float y, float z);

	// Bindings for BasilEngine.Components.Particle
	public:
		static void Bind();

};

#endif // BasilEngine_Components_Particle_GLUE_GEN_HPP

