// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.SceneManagement.Scene
// Generated on: 2025-11-30 21:19:50

#ifndef BasilEngine_SceneManagement_Scene_GLUE_GEN_HPP
#define BasilEngine_SceneManagement_Scene_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.SceneManagement.Scene
#include "Bindings/ManagedScene.hpp"

// Object: BasilEngine_SceneManagement_Scene_GLUE_GEN
class BasilEngine_SceneManagement_Scene_GLUE_GEN {
// Methods for BasilEngine.SceneManagement.Scene
	static void LoadSceneByName(MonoString* sceneName);
	static void LoadSceneByIndex(int32_t index);

	// Bindings for BasilEngine.SceneManagement.Scene
	public:
		static void Bind();

};

#endif // BasilEngine_SceneManagement_Scene_GLUE_GEN_HPP

