// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Input
// Generated on: 2025-11-09 00:41:22

// Includes for the header
#include "BasilEngine_Input_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Input
#include "Bindings/ManagedInput.hpp"


mono_bool BasilEngine_Input_GLUE_GEN::GetKeyInternal(int32_t key)
{
	// Native Method: Name = GetKey
	// Static Accessor: Name = ManagedInput, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedInput::GetKey(key));
}

mono_bool BasilEngine_Input_GLUE_GEN::GetKeyOnce(int32_t key)
{
	// Native Method: Name = GetKeyPress
	// Static Accessor: Name = ManagedInput, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedInput::GetKeyPress(key));
}

void BasilEngine_Input_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Input
	mono_add_internal_call("BasilEngine.Input::GetKeyInternal", (void*)GetKeyInternal);
	mono_add_internal_call("BasilEngine.Input::GetKeyOnce", (void*)GetKeyOnce);

}

