// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Time
// Generated on: 2026-03-06 16:13:28

#ifndef BasilEngine_Time_GLUE_GEN_HPP
#define BasilEngine_Time_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Time
#include "Bindings/ManagedTime.hpp"

// Object: BasilEngine_Time_GLUE_GEN
class BasilEngine_Time_GLUE_GEN {
// Methods for BasilEngine.Time
	static float GetDeltaTimeInternal();

	// Bindings for BasilEngine.Time
	public:
		static void Bind();

};

#endif // BasilEngine_Time_GLUE_GEN_HPP

