// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Audio
// Generated on: 2026-03-12 16:27:30

#ifndef BasilEngine_Components_Audio_GLUE_GEN_HPP
#define BasilEngine_Components_Audio_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Components.Audio
#include "Bindings/ManagedAudio.hpp"

// Object: BasilEngine_Components_Audio_GLUE_GEN
class BasilEngine_Components_Audio_GLUE_GEN {
// Methods for BasilEngine.Components.Audio
	static void setVolume(uint64_t handle, float volume);
	static float getVolume(uint64_t handle);
	static void SetIsLooping(uint64_t handle, mono_bool isLooping);
	static mono_bool GetIsLooping(uint64_t handle);
	static void InternalPlay(uint64_t handle);
	static void InternalPause(uint64_t handle);
	static void InternalStop(uint64_t handle);
	static void AdjustChannelVolume(uint8_t channel, float percentDelta);
	static void SetFilterType(uint64_t handle, int32_t filterType);
	static int32_t GetFilterType(uint64_t handle);
	static void SetFilterCutoff(uint64_t handle, float cutoffHz);
	static float GetFilterCutoff(uint64_t handle);
	static void SetFilterResonance(uint64_t handle, float resonance);
	static float GetFilterResonance(uint64_t handle);

	// Bindings for BasilEngine.Components.Audio
	public:
		static void Bind();

};

#endif // BasilEngine_Components_Audio_GLUE_GEN_HPP

