// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Animation
// Generated on: 2026-03-12 16:27:30

// Includes for the header
#include "BasilEngine_Components_Animation_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Components.Animation
#include "Bindings/ManagedAnimation.hpp"


void BasilEngine_Components_Animation_GLUE_GEN::Play(uint64_t handle)
{
	// Static Accessor: Name = ManagedAnimation, Type = DoubleColon
	ManagedAnimation::Play(handle);
}

void BasilEngine_Components_Animation_GLUE_GEN::Pause(uint64_t handle)
{
	// Static Accessor: Name = ManagedAnimation, Type = DoubleColon
	ManagedAnimation::Pause(handle);
}

void BasilEngine_Components_Animation_GLUE_GEN::Stop(uint64_t handle)
{
	// Static Accessor: Name = ManagedAnimation, Type = DoubleColon
	ManagedAnimation::Stop(handle);
}

void BasilEngine_Components_Animation_GLUE_GEN::SetLoop(uint64_t handle, mono_bool loop)
{
	// Static Accessor: Name = ManagedAnimation, Type = DoubleColon
	ManagedAnimation::SetLoop(handle, loop);
}

void BasilEngine_Components_Animation_GLUE_GEN::SetPlaybackSpeed(uint64_t handle, float speed)
{
	// Static Accessor: Name = ManagedAnimation, Type = DoubleColon
	ManagedAnimation::SetPlaybackSpeed(handle, speed);
}

mono_bool BasilEngine_Components_Animation_GLUE_GEN::IsAnimationFinished(uint64_t handle)
{
	// Static Accessor: Name = ManagedAnimation, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedAnimation::IsAnimationFinished(handle));
}

mono_bool BasilEngine_Components_Animation_GLUE_GEN::PlayAnimation(uint64_t handle, MonoString* animationName, mono_bool shouldLoop)
{
	// Static Accessor: Name = ManagedAnimation, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedAnimation::PlayAnimation(handle, animationName, shouldLoop));
}

mono_bool BasilEngine_Components_Animation_GLUE_GEN::HasAnimation(uint64_t handle, MonoString* animationName)
{
	// Static Accessor: Name = ManagedAnimation, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedAnimation::HasAnimation(handle, animationName));
}

void BasilEngine_Components_Animation_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Components.Animation
	mono_add_internal_call("BasilEngine.Components.Animation::Play", (void*)Play);
	mono_add_internal_call("BasilEngine.Components.Animation::Pause", (void*)Pause);
	mono_add_internal_call("BasilEngine.Components.Animation::Stop", (void*)Stop);
	mono_add_internal_call("BasilEngine.Components.Animation::SetLoop", (void*)SetLoop);
	mono_add_internal_call("BasilEngine.Components.Animation::SetPlaybackSpeed", (void*)SetPlaybackSpeed);
	mono_add_internal_call("BasilEngine.Components.Animation::IsAnimationFinished", (void*)IsAnimationFinished);
	mono_add_internal_call("BasilEngine.Components.Animation::PlayAnimation", (void*)PlayAnimation);
	mono_add_internal_call("BasilEngine.Components.Animation::HasAnimation", (void*)HasAnimation);

}

