// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Rigidbody
// Generated on: 2026-02-28 18:06:36

// Includes for the header
#include "BasilEngine_Components_Rigidbody_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Components.Rigidbody
#include "Bindings/ManagedPhysics.hpp"


void BasilEngine_Components_Rigidbody_GLUE_GEN::SetMotionType(uint64_t handle, int32_t motionType)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetMotionType(handle, motionType);
}

int32_t BasilEngine_Components_Rigidbody_GLUE_GEN::GetMotionType(uint64_t handle)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedPhysics::GetMotionType(handle));
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::SetMass(uint64_t handle, float mass)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetMass(handle, mass);
}

float BasilEngine_Components_Rigidbody_GLUE_GEN::GetMass(uint64_t handle)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedPhysics::GetMass(handle));
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::SetDrag(uint64_t handle, float drag)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetDrag(handle, drag);
}

float BasilEngine_Components_Rigidbody_GLUE_GEN::GetDrag(uint64_t handle)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedPhysics::GetDrag(handle));
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::SetFriction(uint64_t handle, float friction)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetFriction(handle, friction);
}

float BasilEngine_Components_Rigidbody_GLUE_GEN::GetFriction(uint64_t handle)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedPhysics::GetFriction(handle));
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::SetAngularDrag(uint64_t handle, float angularDrag)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetAngularDrag(handle, angularDrag);
}

float BasilEngine_Components_Rigidbody_GLUE_GEN::GetAngularDrag(uint64_t handle)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedPhysics::GetAngularDrag(handle));
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::SetGravityFactor(uint64_t handle, float useAutoGravity)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetGravityFactor(handle, useAutoGravity);
}

float BasilEngine_Components_Rigidbody_GLUE_GEN::GetGravityFactor(uint64_t handle)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedPhysics::GetGravityFactor(handle));
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::SetUseGravity(uint64_t handle, mono_bool useGravity)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetUseGravity(handle, useGravity);
}

mono_bool BasilEngine_Components_Rigidbody_GLUE_GEN::GetUseGravity(uint64_t handle)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedPhysics::GetUseGravity(handle));
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::SetIsKinematic(uint64_t handle, mono_bool isKinematic)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetIsKinematic(handle, isKinematic);
}

mono_bool BasilEngine_Components_Rigidbody_GLUE_GEN::GetIsKinematic(uint64_t handle)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedPhysics::GetIsKinematic(handle));
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::SetFreezeX(uint64_t handle, mono_bool freezeX)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetFreezeX(handle, freezeX);
}

mono_bool BasilEngine_Components_Rigidbody_GLUE_GEN::GetFreezeX(uint64_t handle)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedPhysics::GetFreezeX(handle));
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::SetFreezeY(uint64_t handle, mono_bool freezeY)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetFreezeY(handle, freezeY);
}

mono_bool BasilEngine_Components_Rigidbody_GLUE_GEN::GetFreezeY(uint64_t handle)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedPhysics::GetFreezeY(handle));
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::SetFreezeZ(uint64_t handle, mono_bool freezeZ)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetFreezeZ(handle, freezeZ);
}

mono_bool BasilEngine_Components_Rigidbody_GLUE_GEN::GetFreezeZ(uint64_t handle)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedPhysics::GetFreezeZ(handle));
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::SetFreezeRotationX(uint64_t handle, mono_bool freezeRotationX)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetFreezeRotationX(handle, freezeRotationX);
}

mono_bool BasilEngine_Components_Rigidbody_GLUE_GEN::GetFreezeRotationX(uint64_t handle)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedPhysics::GetFreezeRotationX(handle));
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::SetFreezeRotationY(uint64_t handle, mono_bool freezeRotationY)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetFreezeRotationY(handle, freezeRotationY);
}

mono_bool BasilEngine_Components_Rigidbody_GLUE_GEN::GetFreezeRotationY(uint64_t handle)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedPhysics::GetFreezeRotationY(handle));
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::SetFreezeRotationZ(uint64_t handle, mono_bool freezeRotationZ)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetFreezeRotationZ(handle, freezeRotationZ);
}

mono_bool BasilEngine_Components_Rigidbody_GLUE_GEN::GetFreezeRotationZ(uint64_t handle)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedPhysics::GetFreezeRotationZ(handle));
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::SetLinearDamping(uint64_t handle, float linearDamping)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetLinearDamping(handle, linearDamping);
}

float BasilEngine_Components_Rigidbody_GLUE_GEN::GetLinearDamping(uint64_t handle)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedPhysics::GetLinearDamping(handle));
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::SetCenterOfMass(uint64_t handle, float x, float y, float z)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetCenterOfMass(handle, x, y, z);
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::GetCenterOfMass(uint64_t handle, float* x, float* y, float* z)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::GetCenterOfMass(handle, x, y, z);
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::SetLinearVelocity(uint64_t handle, float x, float y, float z)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetLinearVelocity(handle, x, y, z);
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::GetLinearVelocity(uint64_t handle, float* x, float* y, float* z)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::GetLinearVelocity(handle, x, y, z);
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::SetAngularVelocity(uint64_t handle, float x, float y, float z)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::SetAngularVelocity(handle, x, y, z);
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::GetAngularVelocity(uint64_t handle, float* x, float* y, float* z)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::GetAngularVelocity(handle, x, y, z);
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::AddForceInternal(uint64_t handle, float x, float y, float z)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::AddForceInternal(handle, x, y, z);
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::AddImpulseInternal(uint64_t handle, float x, float y, float z)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	ManagedPhysics::AddImpulseInternal(handle, x, y, z);
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::MovePositionInternal(uint64_t handle, float x, float y, float z)
{
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	// Native Method: Name = MovePosition
	ManagedPhysics::MovePosition(handle, x, y, z);
}

void BasilEngine_Components_Rigidbody_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Components.Rigidbody
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetMotionType", (void*)SetMotionType);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetMotionType", (void*)GetMotionType);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetMass", (void*)SetMass);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetMass", (void*)GetMass);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetDrag", (void*)SetDrag);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetDrag", (void*)GetDrag);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetFriction", (void*)SetFriction);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetFriction", (void*)GetFriction);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetAngularDrag", (void*)SetAngularDrag);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetAngularDrag", (void*)GetAngularDrag);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetGravityFactor", (void*)SetGravityFactor);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetGravityFactor", (void*)GetGravityFactor);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetUseGravity", (void*)SetUseGravity);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetUseGravity", (void*)GetUseGravity);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetIsKinematic", (void*)SetIsKinematic);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetIsKinematic", (void*)GetIsKinematic);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetFreezeX", (void*)SetFreezeX);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetFreezeX", (void*)GetFreezeX);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetFreezeY", (void*)SetFreezeY);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetFreezeY", (void*)GetFreezeY);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetFreezeZ", (void*)SetFreezeZ);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetFreezeZ", (void*)GetFreezeZ);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetFreezeRotationX", (void*)SetFreezeRotationX);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetFreezeRotationX", (void*)GetFreezeRotationX);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetFreezeRotationY", (void*)SetFreezeRotationY);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetFreezeRotationY", (void*)GetFreezeRotationY);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetFreezeRotationZ", (void*)SetFreezeRotationZ);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetFreezeRotationZ", (void*)GetFreezeRotationZ);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetLinearDamping", (void*)SetLinearDamping);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetLinearDamping", (void*)GetLinearDamping);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetCenterOfMass", (void*)SetCenterOfMass);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetCenterOfMass", (void*)GetCenterOfMass);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetLinearVelocity", (void*)SetLinearVelocity);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetLinearVelocity", (void*)GetLinearVelocity);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::SetAngularVelocity", (void*)SetAngularVelocity);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::GetAngularVelocity", (void*)GetAngularVelocity);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::AddForceInternal", (void*)AddForceInternal);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::AddImpulseInternal", (void*)AddImpulseInternal);
	mono_add_internal_call("BasilEngine.Components.Rigidbody::MovePositionInternal", (void*)MovePositionInternal);

}

