// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Input
// Generated on: 2026-03-06 10:40:21

// Includes for the header
#include "BasilEngine_Input_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Input
#include "Bindings/ManagedInput.hpp"


mono_bool BasilEngine_Input_GLUE_GEN::GetKeyInternal(int32_t key)
{
	// Native Method: Name = GetKey
	// Static Accessor: Name = ManagedInput, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedInput::GetKey(key));
}

mono_bool BasilEngine_Input_GLUE_GEN::GetKeyOnce(int32_t key)
{
	// Native Method: Name = GetKeyPress
	// Static Accessor: Name = ManagedInput, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedInput::GetKeyPress(key));
}

void BasilEngine_Input_GLUE_GEN::GetMouseScreenPosInternal(float* x, float* y)
{
	// Native Method: Name = GetMousePosition
	// Static Accessor: Name = ManagedInput, Type = DoubleColon
	ManagedInput::GetMousePosition(x, y);
}

void BasilEngine_Input_GLUE_GEN::SetCursorLockedInternal(mono_bool locked)
{
	// Native Method: Name = LockCursor
	// Static Accessor: Name = ManagedInput, Type = DoubleColon
	ManagedInput::LockCursor(locked);
}

void BasilEngine_Input_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Input
	mono_add_internal_call("BasilEngine.Input::GetKeyInternal", (void*)GetKeyInternal);
	mono_add_internal_call("BasilEngine.Input::GetKeyOnce", (void*)GetKeyOnce);
	mono_add_internal_call("BasilEngine.Input::GetMouseScreenPosInternal", (void*)GetMouseScreenPosInternal);
	mono_add_internal_call("BasilEngine.Input::SetCursorLockedInternal", (void*)SetCursorLockedInternal);

}

