// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Time
// Generated on: 2026-02-08 17:03:57

// Includes for the header
#include "BasilEngine_Time_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Time
#include "Bindings/ManagedTime.hpp"


float BasilEngine_Time_GLUE_GEN::GetDeltaTimeInternal()
{
	// Native Method: Name = GetDeltaTime
	// Static Accessor: Name = ManagedTime, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedTime::GetDeltaTime());
}

void BasilEngine_Time_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Time
	mono_add_internal_call("BasilEngine.Time::GetDeltaTimeInternal", (void*)GetDeltaTimeInternal);

}

