// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Camera
// Generated on: 2026-03-01 02:06:02

// Includes for the header
#include "BasilEngine_Components_Camera_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Components.Camera
#include "Bindings/ManagedCamera.hpp"


void BasilEngine_Components_Camera_GLUE_GEN::Internal_SetType(uint64_t handle, int32_t type)
{
	// Native Method: Name = SetCameraType
	// Static Accessor: Name = ManagedCamera, Type = DoubleColon
	ManagedCamera::SetCameraType(handle, type);
}

int32_t BasilEngine_Components_Camera_GLUE_GEN::Internal_GetType(uint64_t handle)
{
	// Native Method: Name = GetCameraType
	// Static Accessor: Name = ManagedCamera, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedCamera::GetCameraType(handle));
}

void BasilEngine_Components_Camera_GLUE_GEN::Internal_SetFOV(uint64_t handle, float fov)
{
	// Native Method: Name = setFoV
	// Static Accessor: Name = ManagedCamera, Type = DoubleColon
	ManagedCamera::setFoV(handle, fov);
}

float BasilEngine_Components_Camera_GLUE_GEN::Internal_GetFOV(uint64_t handle)
{
	// Native Method: Name = getFoV
	// Static Accessor: Name = ManagedCamera, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedCamera::getFoV(handle));
}

void BasilEngine_Components_Camera_GLUE_GEN::Internal_SetAspectRatio(uint64_t handle, float ratio)
{
	// Native Method: Name = setAspectRatio
	// Static Accessor: Name = ManagedCamera, Type = DoubleColon
	ManagedCamera::setAspectRatio(handle, ratio);
}

float BasilEngine_Components_Camera_GLUE_GEN::Internal_GetAspectRatio(uint64_t handle)
{
	// Native Method: Name = getAspectRatio
	// Static Accessor: Name = ManagedCamera, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedCamera::getAspectRatio(handle));
}

void BasilEngine_Components_Camera_GLUE_GEN::Internal_SetNearPlane(uint64_t handle, float near)
{
	// Native Method: Name = setNear
	// Static Accessor: Name = ManagedCamera, Type = DoubleColon
	ManagedCamera::setNear(handle, near);
}

void BasilEngine_Components_Camera_GLUE_GEN::Internal_SetFarPlane(uint64_t handle, float far)
{
	// Native Method: Name = setFar
	// Static Accessor: Name = ManagedCamera, Type = DoubleColon
	ManagedCamera::setFar(handle, far);
}

float BasilEngine_Components_Camera_GLUE_GEN::Internal_GetNearPlane(uint64_t handle)
{
	// Native Method: Name = getNear
	// Static Accessor: Name = ManagedCamera, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedCamera::getNear(handle));
}

float BasilEngine_Components_Camera_GLUE_GEN::Internal_GetFarPlane(uint64_t handle)
{
	// Native Method: Name = getFar
	// Static Accessor: Name = ManagedCamera, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedCamera::getFar(handle));
}

void BasilEngine_Components_Camera_GLUE_GEN::Internal_ScreenToWorldPoint(uint64_t handle, float x, float y, float depth, float* wx, float* wy, float* wz)
{
	// Native Method: Name = ScreenToWorldPoint
	// Static Accessor: Name = ManagedCamera, Type = DoubleColon
	ManagedCamera::ScreenToWorldPoint(handle, x, y, depth, wx, wy, wz);
}

void BasilEngine_Components_Camera_GLUE_GEN::Internal_ScreenPointToRay(uint64_t handle, float x, float y, float _unusedDepth, float* ox, float* oy, float* oz, float* dx, float* dy, float* dz)
{
	// Native Method: Name = ScreenPointToRay
	// Static Accessor: Name = ManagedCamera, Type = DoubleColon
	ManagedCamera::ScreenPointToRay(handle, x, y, _unusedDepth, ox, oy, oz, dx, dy, dz);
}

void BasilEngine_Components_Camera_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Components.Camera
	mono_add_internal_call("BasilEngine.Components.Camera::Internal_SetType", (void*)Internal_SetType);
	mono_add_internal_call("BasilEngine.Components.Camera::Internal_GetType", (void*)Internal_GetType);
	mono_add_internal_call("BasilEngine.Components.Camera::Internal_SetFOV", (void*)Internal_SetFOV);
	mono_add_internal_call("BasilEngine.Components.Camera::Internal_GetFOV", (void*)Internal_GetFOV);
	mono_add_internal_call("BasilEngine.Components.Camera::Internal_SetAspectRatio", (void*)Internal_SetAspectRatio);
	mono_add_internal_call("BasilEngine.Components.Camera::Internal_GetAspectRatio", (void*)Internal_GetAspectRatio);
	mono_add_internal_call("BasilEngine.Components.Camera::Internal_SetNearPlane", (void*)Internal_SetNearPlane);
	mono_add_internal_call("BasilEngine.Components.Camera::Internal_SetFarPlane", (void*)Internal_SetFarPlane);
	mono_add_internal_call("BasilEngine.Components.Camera::Internal_GetNearPlane", (void*)Internal_GetNearPlane);
	mono_add_internal_call("BasilEngine.Components.Camera::Internal_GetFarPlane", (void*)Internal_GetFarPlane);
	mono_add_internal_call("BasilEngine.Components.Camera::Internal_ScreenToWorldPoint", (void*)Internal_ScreenToWorldPoint);
	mono_add_internal_call("BasilEngine.Components.Camera::Internal_ScreenPointToRay", (void*)Internal_ScreenPointToRay);

}

