// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Animation
// Generated on: 2026-03-31 05:57:26

#ifndef BasilEngine_Components_Animation_GLUE_GEN_HPP
#define BasilEngine_Components_Animation_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Components.Animation
#include "Bindings/ManagedAnimation.hpp"

// Object: BasilEngine_Components_Animation_GLUE_GEN
class BasilEngine_Components_Animation_GLUE_GEN {
// Methods for BasilEngine.Components.Animation
	static void Play(uint64_t handle);
	static void Pause(uint64_t handle);
	static void Stop(uint64_t handle);
	static void SetLoop(uint64_t handle, mono_bool loop);
	static void SetPlaybackSpeed(uint64_t handle, float speed);
	static mono_bool IsAnimationFinished(uint64_t handle);
	static mono_bool PlayAnimation(uint64_t handle, MonoString* animationName, mono_bool shouldLoop);
	static mono_bool HasAnimation(uint64_t handle, MonoString* animationName);
	static void SetSpritesheetMode(uint64_t handle, mono_bool enabled);
	static mono_bool GetSpritesheetMode(uint64_t handle);

	// Bindings for BasilEngine.Components.Animation
	public:
		static void Bind();

};

#endif // BasilEngine_Components_Animation_GLUE_GEN_HPP

