// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Physics
// Generated on: 2026-01-23 14:48:37

// Includes for the header
#include "BasilEngine_Physics_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Physics
#include "Bindings/ManagedPhysics.hpp"


mono_bool BasilEngine_Physics_GLUE_GEN::Internal_Raycast(float ox, float oy, float oz, float dx, float dy, float dz, float maxDistance, mono_bool ignoreTriggers, uint64_t* entity, float* px, float* py, float* pz, float* nx, float* ny, float* nz, float* distance, uint8_t* isTrigger)
{
	// Native Method: Name = Raycast
	// Static Accessor: Name = ManagedPhysics, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedPhysics::Raycast(ox, oy, oz, dx, dy, dz, maxDistance, ignoreTriggers, entity, px, py, pz, nx, ny, nz, distance, isTrigger));
}

void BasilEngine_Physics_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Physics
	mono_add_internal_call("BasilEngine.Physics::Internal_Raycast", (void*)Internal_Raycast);

}

