// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Light
// Generated on: 2026-03-16 23:01:11

// Includes for the header
#include "BasilEngine_Components_Light_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Components.Light
#include "Bindings/ManagedLight.hpp"


void BasilEngine_Components_Light_GLUE_GEN::Internal_SetType(uint64_t handle, int32_t type)
{
	// Native Method: Name = SetLightType
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	ManagedLight::SetLightType(handle, type);
}

int32_t BasilEngine_Components_Light_GLUE_GEN::Internal_GetType(uint64_t handle)
{
	// Native Method: Name = GetLightType
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	return 	ManagedLight::GetLightType(handle);
}

mono_bool BasilEngine_Components_Light_GLUE_GEN::Internal_GetEnabled(uint64_t handle)
{
	// Native Method: Name = GetEnabled
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	return 	ManagedLight::GetEnabled(handle);
}

void BasilEngine_Components_Light_GLUE_GEN::Internal_SetEnabled(uint64_t handle, mono_bool v)
{
	// Native Method: Name = SetEnabled
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	ManagedLight::SetEnabled(handle, v);
}

float BasilEngine_Components_Light_GLUE_GEN::Internal_GetColorR(uint64_t handle)
{
	// Native Method: Name = GetColorR
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	return 	ManagedLight::GetColorR(handle);
}

float BasilEngine_Components_Light_GLUE_GEN::Internal_GetColorG(uint64_t handle)
{
	// Native Method: Name = GetColorG
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	return 	ManagedLight::GetColorG(handle);
}

float BasilEngine_Components_Light_GLUE_GEN::Internal_GetColorB(uint64_t handle)
{
	// Native Method: Name = GetColorB
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	return 	ManagedLight::GetColorB(handle);
}

void BasilEngine_Components_Light_GLUE_GEN::Internal_SetColor(uint64_t handle, float r, float g, float b)
{
	// Native Method: Name = SetColor
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	ManagedLight::SetColor(handle, r, g, b);
}

void BasilEngine_Components_Light_GLUE_GEN::Internal_SetColorR(uint64_t handle, float r)
{
	// Native Method: Name = SetColorR
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	ManagedLight::SetColorR(handle, r);
}

void BasilEngine_Components_Light_GLUE_GEN::Internal_SetColorG(uint64_t handle, float g)
{
	// Native Method: Name = SetColorG
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	ManagedLight::SetColorG(handle, g);
}

void BasilEngine_Components_Light_GLUE_GEN::Internal_SetColorB(uint64_t handle, float b)
{
	// Native Method: Name = SetColorB
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	ManagedLight::SetColorB(handle, b);
}

float BasilEngine_Components_Light_GLUE_GEN::Internal_GetIntensity(uint64_t handle)
{
	// Native Method: Name = GetIntensity
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	return 	ManagedLight::GetIntensity(handle);
}

void BasilEngine_Components_Light_GLUE_GEN::Internal_SetIntensity(uint64_t handle, float v)
{
	// Native Method: Name = SetIntensity
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	ManagedLight::SetIntensity(handle, v);
}

float BasilEngine_Components_Light_GLUE_GEN::Internal_GetDirectionX(uint64_t handle)
{
	// Native Method: Name = GetDirectionX
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	return 	ManagedLight::GetDirectionX(handle);
}

float BasilEngine_Components_Light_GLUE_GEN::Internal_GetDirectionY(uint64_t handle)
{
	// Native Method: Name = GetDirectionY
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	return 	ManagedLight::GetDirectionY(handle);
}

float BasilEngine_Components_Light_GLUE_GEN::Internal_GetDirectionZ(uint64_t handle)
{
	// Native Method: Name = GetDirectionZ
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	return 	ManagedLight::GetDirectionZ(handle);
}

void BasilEngine_Components_Light_GLUE_GEN::Internal_SetDirection(uint64_t handle, float x, float y, float z)
{
	// Native Method: Name = SetDirection
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	ManagedLight::SetDirection(handle, x, y, z);
}

float BasilEngine_Components_Light_GLUE_GEN::Internal_GetRange(uint64_t handle)
{
	// Native Method: Name = GetRange
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	return 	ManagedLight::GetRange(handle);
}

void BasilEngine_Components_Light_GLUE_GEN::Internal_SetRange(uint64_t handle, float v)
{
	// Native Method: Name = SetRange
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	ManagedLight::SetRange(handle, v);
}

float BasilEngine_Components_Light_GLUE_GEN::Internal_GetInnerConeDeg(uint64_t handle)
{
	// Native Method: Name = GetInnerConeDeg
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	return 	ManagedLight::GetInnerConeDeg(handle);
}

float BasilEngine_Components_Light_GLUE_GEN::Internal_GetOuterConeDeg(uint64_t handle)
{
	// Native Method: Name = GetOuterConeDeg
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	return 	ManagedLight::GetOuterConeDeg(handle);
}

void BasilEngine_Components_Light_GLUE_GEN::Internal_SetCones(uint64_t handle, float innerDeg, float outerDeg)
{
	// Native Method: Name = SetCones
	// Static Accessor: Name = ManagedLight, Type = DoubleColon
	ManagedLight::SetCones(handle, innerDeg, outerDeg);
}

void BasilEngine_Components_Light_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Components.Light
	mono_add_internal_call("BasilEngine.Components.Light::Internal_SetType", (void*)Internal_SetType);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_GetType", (void*)Internal_GetType);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_GetEnabled", (void*)Internal_GetEnabled);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_SetEnabled", (void*)Internal_SetEnabled);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_GetColorR", (void*)Internal_GetColorR);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_GetColorG", (void*)Internal_GetColorG);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_GetColorB", (void*)Internal_GetColorB);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_SetColor", (void*)Internal_SetColor);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_SetColorR", (void*)Internal_SetColorR);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_SetColorG", (void*)Internal_SetColorG);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_SetColorB", (void*)Internal_SetColorB);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_GetIntensity", (void*)Internal_GetIntensity);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_SetIntensity", (void*)Internal_SetIntensity);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_GetDirectionX", (void*)Internal_GetDirectionX);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_GetDirectionY", (void*)Internal_GetDirectionY);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_GetDirectionZ", (void*)Internal_GetDirectionZ);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_SetDirection", (void*)Internal_SetDirection);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_GetRange", (void*)Internal_GetRange);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_SetRange", (void*)Internal_SetRange);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_GetInnerConeDeg", (void*)Internal_GetInnerConeDeg);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_GetOuterConeDeg", (void*)Internal_GetOuterConeDeg);
	mono_add_internal_call("BasilEngine.Components.Light::Internal_SetCones", (void*)Internal_SetCones);

}

