// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Debug.Logger
// Generated on: 2026-03-13 12:06:05

// Includes for the header
#include "BasilEngine_Debug_Logger_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Debug.Logger
#include "Bindings/MANAGED_CONSOLE.hpp"


void BasilEngine_Debug_Logger_GLUE_GEN::internal_Log(MonoString* message)
{
	// Native Method: Name = LogInfo
	// Static Accessor: Name = ManagedConsole, Type = DoubleColon
	ManagedConsole::LogInfo(message);
}

void BasilEngine_Debug_Logger_GLUE_GEN::internal_Warn(MonoString* message)
{
	// Native Method: Name = LogWarning
	// Static Accessor: Name = ManagedConsole, Type = DoubleColon
	ManagedConsole::LogWarning(message);
}

void BasilEngine_Debug_Logger_GLUE_GEN::internal_Error(MonoString* message)
{
	// Native Method: Name = LogError
	// Static Accessor: Name = ManagedConsole, Type = DoubleColon
	ManagedConsole::LogError(message);
}

void BasilEngine_Debug_Logger_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Debug.Logger
	mono_add_internal_call("BasilEngine.Debug.Logger::internal_Log", (void*)internal_Log);
	mono_add_internal_call("BasilEngine.Debug.Logger::internal_Warn", (void*)internal_Warn);
	mono_add_internal_call("BasilEngine.Debug.Logger::internal_Error", (void*)internal_Error);

}

