// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Video
// Generated on: 2026-02-05 14:38:50

#ifndef BasilEngine_Components_Video_GLUE_GEN_HPP
#define BasilEngine_Components_Video_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Components.Video
#include "Bindings/ManagedVideo.hpp"

// Object: BasilEngine_Components_Video_GLUE_GEN
class BasilEngine_Components_Video_GLUE_GEN {
// Methods for BasilEngine.Components.Video
	static mono_bool GetIsPlayingInternal(uint64_t handle);
	static void SetPlayingInternal(uint64_t handle, mono_bool value);
	static void SetLoopInternal(uint64_t handle, mono_bool value);

	// Bindings for BasilEngine.Components.Video
	public:
		static void Bind();

};

#endif // BasilEngine_Components_Video_GLUE_GEN_HPP

