// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Transform
// Generated on: 2026-02-02 20:19:26

// Includes for the header
#include "BasilEngine_Components_Transform_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Components.Transform
#include "Bindings/ManagedTransform.hpp"


void BasilEngine_Components_Transform_GLUE_GEN::SetPosition(uint64_t handle, float x, float y, float z)
{
	// Native Method: Name = SetPosition
	// Static Accessor: Name = ManagedTransform, Type = DoubleColon
	ManagedTransform::SetPosition(handle, x, y, z);
}

void BasilEngine_Components_Transform_GLUE_GEN::GetPosition(uint64_t handle, float* x, float* y, float* z)
{
	// Native Method: Name = GetPosition
	// Static Accessor: Name = ManagedTransform, Type = DoubleColon
	ManagedTransform::GetPosition(handle, x, y, z);
}

void BasilEngine_Components_Transform_GLUE_GEN::SetRotationInternal(uint64_t handle, float x, float y, float z)
{
	// Native Method: Name = SetRotation
	// Static Accessor: Name = ManagedTransform, Type = DoubleColon
	ManagedTransform::SetRotation(handle, x, y, z);
}

void BasilEngine_Components_Transform_GLUE_GEN::GetRotationInternal(uint64_t handle, float* x, float* y, float* z)
{
	// Native Method: Name = GetRotation
	// Static Accessor: Name = ManagedTransform, Type = DoubleColon
	ManagedTransform::GetRotation(handle, x, y, z);
}

void BasilEngine_Components_Transform_GLUE_GEN::SetScaleInternal(uint64_t handle, float x, float y, float z)
{
	// Native Method: Name = SetScale
	// Static Accessor: Name = ManagedTransform, Type = DoubleColon
	ManagedTransform::SetScale(handle, x, y, z);
}

void BasilEngine_Components_Transform_GLUE_GEN::GetScaleInternal(uint64_t handle, float* x, float* y, float* z)
{
	// Native Method: Name = GetScale
	// Static Accessor: Name = ManagedTransform, Type = DoubleColon
	ManagedTransform::GetScale(handle, x, y, z);
}

void BasilEngine_Components_Transform_GLUE_GEN::GetForwardInternal(uint64_t handle, float* x, float* y, float* z)
{
	// Native Method: Name = GetForward
	// Static Accessor: Name = ManagedTransform, Type = DoubleColon
	ManagedTransform::GetForward(handle, x, y, z);
}

void BasilEngine_Components_Transform_GLUE_GEN::GetRightInternal(uint64_t handle, float* x, float* y, float* z)
{
	// Native Method: Name = GetRight
	// Static Accessor: Name = ManagedTransform, Type = DoubleColon
	ManagedTransform::GetRight(handle, x, y, z);
}

void BasilEngine_Components_Transform_GLUE_GEN::GetUpInternal(uint64_t handle, float* x, float* y, float* z)
{
	// Native Method: Name = GetUp
	// Static Accessor: Name = ManagedTransform, Type = DoubleColon
	ManagedTransform::GetUp(handle, x, y, z);
}

void BasilEngine_Components_Transform_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Components.Transform
	mono_add_internal_call("BasilEngine.Components.Transform::SetPosition", (void*)SetPosition);
	mono_add_internal_call("BasilEngine.Components.Transform::GetPosition", (void*)GetPosition);
	mono_add_internal_call("BasilEngine.Components.Transform::SetRotationInternal", (void*)SetRotationInternal);
	mono_add_internal_call("BasilEngine.Components.Transform::GetRotationInternal", (void*)GetRotationInternal);
	mono_add_internal_call("BasilEngine.Components.Transform::SetScaleInternal", (void*)SetScaleInternal);
	mono_add_internal_call("BasilEngine.Components.Transform::GetScaleInternal", (void*)GetScaleInternal);
	mono_add_internal_call("BasilEngine.Components.Transform::GetForwardInternal", (void*)GetForwardInternal);
	mono_add_internal_call("BasilEngine.Components.Transform::GetRightInternal", (void*)GetRightInternal);
	mono_add_internal_call("BasilEngine.Components.Transform::GetUpInternal", (void*)GetUpInternal);

}

