// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.WorldUI
// Generated on: 2026-03-20 17:59:37

#ifndef BasilEngine_Components_WorldUI_GLUE_GEN_HPP
#define BasilEngine_Components_WorldUI_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Components.WorldUI
#include "Bindings/ManagedWorldUI.hpp"

// Object: BasilEngine_Components_WorldUI_GLUE_GEN
class BasilEngine_Components_WorldUI_GLUE_GEN {
// Methods for BasilEngine.Components.WorldUI
	static void SetScaleInternal(uint64_t handle, float x, float y);
	static void GetScaleInternal(uint64_t handle, float* x, float* y);
	static void SetVisibleInternal(uint64_t handle, mono_bool visibility);
	static mono_bool GetVisibleInternal(uint64_t handle);

	// Bindings for BasilEngine.Components.WorldUI
	public:
		static void Bind();

};

#endif // BasilEngine_Components_WorldUI_GLUE_GEN_HPP

