// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Rigidbody
// Generated on: 2026-03-10 15:26:08

#ifndef BasilEngine_Components_Rigidbody_GLUE_GEN_HPP
#define BasilEngine_Components_Rigidbody_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Components.Rigidbody
#include "Bindings/ManagedPhysics.hpp"

// Object: BasilEngine_Components_Rigidbody_GLUE_GEN
class BasilEngine_Components_Rigidbody_GLUE_GEN {
// Methods for BasilEngine.Components.Rigidbody
	static void SetMotionType(uint64_t handle, int32_t motionType);
	static int32_t GetMotionType(uint64_t handle);
	static void SetMass(uint64_t handle, float mass);
	static float GetMass(uint64_t handle);
	static void SetDrag(uint64_t handle, float drag);
	static float GetDrag(uint64_t handle);
	static void SetFriction(uint64_t handle, float friction);
	static float GetFriction(uint64_t handle);
	static void SetAngularDrag(uint64_t handle, float angularDrag);
	static float GetAngularDrag(uint64_t handle);
	static void SetGravityFactor(uint64_t handle, float useAutoGravity);
	static float GetGravityFactor(uint64_t handle);
	static void SetUseGravity(uint64_t handle, mono_bool useGravity);
	static mono_bool GetUseGravity(uint64_t handle);
	static void SetIsKinematic(uint64_t handle, mono_bool isKinematic);
	static mono_bool GetIsKinematic(uint64_t handle);
	static void SetFreezeX(uint64_t handle, mono_bool freezeX);
	static mono_bool GetFreezeX(uint64_t handle);
	static void SetFreezeY(uint64_t handle, mono_bool freezeY);
	static mono_bool GetFreezeY(uint64_t handle);
	static void SetFreezeZ(uint64_t handle, mono_bool freezeZ);
	static mono_bool GetFreezeZ(uint64_t handle);
	static void SetFreezeRotationX(uint64_t handle, mono_bool freezeRotationX);
	static mono_bool GetFreezeRotationX(uint64_t handle);
	static void SetFreezeRotationY(uint64_t handle, mono_bool freezeRotationY);
	static mono_bool GetFreezeRotationY(uint64_t handle);
	static void SetFreezeRotationZ(uint64_t handle, mono_bool freezeRotationZ);
	static mono_bool GetFreezeRotationZ(uint64_t handle);
	static void SetLinearDamping(uint64_t handle, float linearDamping);
	static float GetLinearDamping(uint64_t handle);
	static void SetCenterOfMass(uint64_t handle, float x, float y, float z);
	static void GetCenterOfMass(uint64_t handle, float* x, float* y, float* z);
	static void SetLinearVelocity(uint64_t handle, float x, float y, float z);
	static void GetLinearVelocity(uint64_t handle, float* x, float* y, float* z);
	static void SetAngularVelocity(uint64_t handle, float x, float y, float z);
	static void GetAngularVelocity(uint64_t handle, float* x, float* y, float* z);
	static void AddForceInternal(uint64_t handle, float x, float y, float z);
	static void AddImpulseInternal(uint64_t handle, float x, float y, float z);
	static void MovePositionInternal(uint64_t handle, float x, float y, float z);

	// Bindings for BasilEngine.Components.Rigidbody
	public:
		static void Bind();

};

#endif // BasilEngine_Components_Rigidbody_GLUE_GEN_HPP

