// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Audio
// Generated on: 2026-02-08 05:55:59

// Includes for the header
#include "BasilEngine_Components_Audio_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Components.Audio
#include "Bindings/ManagedAudio.hpp"


void BasilEngine_Components_Audio_GLUE_GEN::setVolume(uint64_t handle, float volume)
{
	// Native Method: Name = SetVolume
	// Static Accessor: Name = ManagedAudio, Type = DoubleColon
	ManagedAudio::SetVolume(handle, volume);
}

float BasilEngine_Components_Audio_GLUE_GEN::getVolume(uint64_t handle)
{
	// Native Method: Name = GetVolume
	// Static Accessor: Name = ManagedAudio, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedAudio::GetVolume(handle));
}

void BasilEngine_Components_Audio_GLUE_GEN::SetIsLooping(uint64_t handle, mono_bool isLooping)
{
	// Native Method: Name = SetIsLooping
	// Static Accessor: Name = ManagedAudio, Type = DoubleColon
	ManagedAudio::SetIsLooping(handle, isLooping);
}

mono_bool BasilEngine_Components_Audio_GLUE_GEN::GetIsLooping(uint64_t handle)
{
	// Native Method: Name = GetIsLooping
	// Static Accessor: Name = ManagedAudio, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedAudio::GetIsLooping(handle));
}

void BasilEngine_Components_Audio_GLUE_GEN::InternalPlay(uint64_t handle)
{
	// Native Method: Name = Play
	// Static Accessor: Name = ManagedAudio, Type = DoubleColon
	ManagedAudio::Play(handle);
}

void BasilEngine_Components_Audio_GLUE_GEN::InternalPause(uint64_t handle)
{
	// Native Method: Name = Pause
	// Static Accessor: Name = ManagedAudio, Type = DoubleColon
	ManagedAudio::Pause(handle);
}

void BasilEngine_Components_Audio_GLUE_GEN::InternalStop(uint64_t handle)
{
	// Native Method: Name = Stop
	// Static Accessor: Name = ManagedAudio, Type = DoubleColon
	ManagedAudio::Stop(handle);
}

void BasilEngine_Components_Audio_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Components.Audio
	mono_add_internal_call("BasilEngine.Components.Audio::setVolume", (void*)setVolume);
	mono_add_internal_call("BasilEngine.Components.Audio::getVolume", (void*)getVolume);
	mono_add_internal_call("BasilEngine.Components.Audio::SetIsLooping", (void*)SetIsLooping);
	mono_add_internal_call("BasilEngine.Components.Audio::GetIsLooping", (void*)GetIsLooping);
	mono_add_internal_call("BasilEngine.Components.Audio::InternalPlay", (void*)InternalPlay);
	mono_add_internal_call("BasilEngine.Components.Audio::InternalPause", (void*)InternalPause);
	mono_add_internal_call("BasilEngine.Components.Audio::InternalStop", (void*)InternalStop);

}

