// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.MeshRenderer
// Generated on: 2026-03-31 06:03:46

#ifndef BasilEngine_Components_MeshRenderer_GLUE_GEN_HPP
#define BasilEngine_Components_MeshRenderer_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Components.MeshRenderer
#include "Bindings/ManagedMeshRenderer.hpp"

// Object: BasilEngine_Components_MeshRenderer_GLUE_GEN
class BasilEngine_Components_MeshRenderer_GLUE_GEN {
// Methods for BasilEngine.Components.MeshRenderer
	static void Internal_GetAlbedoColor(uint64_t handle, float* r, float* g, float* b);
	static void Internal_SetAlbedoColor(uint64_t handle, float r, float g, float b);
	static float Internal_GetMetallic(uint64_t handle);
	static void Internal_SetMetallic(uint64_t handle, float value);
	static float Internal_GetRoughness(uint64_t handle);
	static void Internal_SetRoughness(uint64_t handle, float value);
	static void Internal_SetFloatOverride(uint64_t handle, MonoString* propertyName, float value);
	static void Internal_SetVec3Override(uint64_t handle, MonoString* propertyName, float x, float y, float z);
	static void Internal_SetVec4Override(uint64_t handle, MonoString* propertyName, float x, float y, float z, float w);
	static mono_bool Internal_HasOverride(uint64_t handle, MonoString* propertyName);
	static void Internal_ClearOverride(uint64_t handle, MonoString* propertyName);
	static void Internal_ClearAllOverrides(uint64_t handle);
	static mono_bool Internal_GetVisible(uint64_t handle);
	static void Internal_SetVisible(uint64_t handle, mono_bool visible);

	// Bindings for BasilEngine.Components.MeshRenderer
	public:
		static void Bind();

};

#endif // BasilEngine_Components_MeshRenderer_GLUE_GEN_HPP

