// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Physics
// Generated on: 2025-11-25 04:44:24

#ifndef BasilEngine_Physics_GLUE_GEN_HPP
#define BasilEngine_Physics_GLUE_GEN_HPP

// Object: BasilEngine_Physics_GLUE_GEN
class BasilEngine_Physics_GLUE_GEN {
	// Bindings for BasilEngine.Physics
	public:
		static void Bind();

};

#endif // BasilEngine_Physics_GLUE_GEN_HPP

