// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Physics
// Generated on: 2025-11-25 04:44:24

// Includes for the header
#include "BasilEngine_Physics_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Physics


void BasilEngine_Physics_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Physics

}

