// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Transform
// Generated on: 2025-11-14 19:11:34

// Includes for the header
#include "BasilEngine_Components_Transform_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.Components.Transform
#include "Bindings/ManagedTransform.hpp"


void BasilEngine_Components_Transform_GLUE_GEN::SetPosition(uint64_t handle, float x, float y, float z)
{
	// Native Method: Name = SetPosition
	// Static Accessor: Name = ManagedTransform, Type = DoubleColon
	ManagedTransform::SetPosition(handle, x, y, z);
}

void BasilEngine_Components_Transform_GLUE_GEN::GetPosition(uint64_t handle, float* x, float* y, float* z)
{
	// Native Method: Name = GetPosition
	// Static Accessor: Name = ManagedTransform, Type = DoubleColon
	ManagedTransform::GetPosition(handle, x, y, z);
}

void BasilEngine_Components_Transform_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.Components.Transform
	mono_add_internal_call("BasilEngine.Components.Transform::SetPosition", (void*)SetPosition);
	mono_add_internal_call("BasilEngine.Components.Transform::GetPosition", (void*)GetPosition);

}

