// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.GameObject
// Generated on: 2026-03-06 16:13:28

// Includes for the header
#include "BasilEngine_GameObject_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for BasilEngine.GameObject
#include "Bindings/ManagedGameObjects.hpp"


uint64_t BasilEngine_GameObject_GLUE_GEN::internal_Find(MonoString* name)
{
	// Native Method: Name = FindByName
	// Static Accessor: Name = ManagedGameObjects, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedGameObjects::FindByName(name));
}

void BasilEngine_GameObject_GLUE_GEN::DeleteGameObjectInternal(uint64_t handle)
{
	// Native Method: Name = DeleteGameObject
	// Static Accessor: Name = ManagedGameObjects, Type = DoubleColon
	ManagedGameObjects::DeleteGameObject(handle);
}

void BasilEngine_GameObject_GLUE_GEN::SetVisibleInternal(uint64_t handle, mono_bool visible)
{
	// Native Method: Name = SetVisible
	// Static Accessor: Name = ManagedGameObjects, Type = DoubleColon
	ManagedGameObjects::SetVisible(handle, visible);
}

mono_bool BasilEngine_GameObject_GLUE_GEN::GetVisibleInternal(uint64_t handle)
{
	// Native Method: Name = GetVisible
	// Static Accessor: Name = ManagedGameObjects, Type = DoubleColon
	return MonoMarshal::NativeToMono(ManagedGameObjects::GetVisible(handle));
}

void BasilEngine_GameObject_GLUE_GEN::Bind()
{
	// Binding for BasilEngine.GameObject
	mono_add_internal_call("BasilEngine.GameObject::internal_Find", (void*)internal_Find);
	mono_add_internal_call("BasilEngine.GameObject::DeleteGameObjectInternal", (void*)DeleteGameObjectInternal);
	mono_add_internal_call("BasilEngine.GameObject::SetVisibleInternal", (void*)SetVisibleInternal);
	mono_add_internal_call("BasilEngine.GameObject::GetVisibleInternal", (void*)GetVisibleInternal);

}

