// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.Component
// Generated on: 2025-11-25 04:44:24

#ifndef BasilEngine_Components_Component_GLUE_GEN_HPP
#define BasilEngine_Components_Component_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Components.Component
#include "Bindings/ManagedComponents.hpp"

// Object: BasilEngine_Components_Component_GLUE_GEN
class BasilEngine_Components_Component_GLUE_GEN {
// Methods for BasilEngine.Components.Component
	static uint32_t Internal_RegisterComponent(MonoString* name);
	static mono_bool Internal_HasComponent(uint64_t handle, uint32_t typeHandle);
	static MonoObject* Internal_GetScriptableComponent(uint64_t handle, MonoString* fullName);

	// Bindings for BasilEngine.Components.Component
	public:
		static void Bind();

};

#endif // BasilEngine_Components_Component_GLUE_GEN_HPP

