// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: BasilEngine.dll
// Type: BasilEngine.Components.HudComponent
// Generated on: 2026-03-07 22:47:31

#ifndef BasilEngine_Components_HudComponent_GLUE_GEN_HPP
#define BasilEngine_Components_HudComponent_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for BasilEngine.Components.HudComponent
#include "Bindings/ManagedHudComponent.hpp"

// Object: BasilEngine_Components_HudComponent_GLUE_GEN
class BasilEngine_Components_HudComponent_GLUE_GEN {
// Methods for BasilEngine.Components.HudComponent
	static void SetVisibleInternal(uint64_t handle, mono_bool visibility);
	static mono_bool GetVisibleInternal(uint64_t handle);
	static void SetPositionInternal(uint64_t handle, float x, float y);
	static void GetPositionInternal(uint64_t handle, float* x, float* y);

	// Bindings for BasilEngine.Components.HudComponent
	public:
		static void Bind();

};

#endif // BasilEngine_Components_HudComponent_GLUE_GEN_HPP

