//// This file is generated by CSBridge.
//// Do not edit this file directly.
//// Generated from: EngineAPI.dll
//// Type: EngineAPI.GameObject
//// Generated on: 2025-09-09 15:01:46
//
//#ifndef EngineAPI_GameObject_GLUE_GEN_HPP
//#define EngineAPI_GameObject_GLUE_GEN_HPP
//
//// Includes for mono API
//#include "mono_include_fwd.h"
//
//// Includes for EngineAPI.GameObject
//#include "Engine/GameObject.h"
//
//// Object: EngineAPI_GameObject_GLUE_GEN
//class EngineAPI_GameObject_GLUE_GEN {
//	// Bindings for EngineAPI.GameObject
//	public:
//		static void Bind();
//
//};
//
//#endif // EngineAPI_GameObject_GLUE_GEN_HPP
//
