//// This file is generated by CSBridge.
//// Do not edit this file directly.
//// Generated from: EngineAPI.dll
//// Type: EngineAPI.Component
//// Generated on: 2025-09-09 15:01:46
//
//#ifndef EngineAPI_Component_GLUE_GEN_HPP
//#define EngineAPI_Component_GLUE_GEN_HPP
//
//// Includes for mono API
//#include "mono_include_fwd.h"
//
//// Includes for EngineAPI.Component
//#include "Engine/Component.h"
//#include "Engine/GameObject.h"
//
//// Object: EngineAPI_Component_GLUE_GEN
//class EngineAPI_Component_GLUE_GEN {
//// Methods for EngineAPI.Component
//	static MonoObject* Get_GO_Internal(MonoObject* _self)
//
//	// Bindings for EngineAPI.Component
//	public:
//		static void Bind();
//
//};
//
//#endif // EngineAPI_Component_GLUE_GEN_HPP
//
