//// This file is generated by CSBridge.
//// Do not edit this file directly.
//// Generated from: EngineAPI.dll
//// Type: EngineAPI.Component
//// Generated on: 2025-09-09 15:01:46
//
//// Includes for the header
//#include "EngineAPI_Component_GLUE_GEN.hpp"
//
//// Mono package include
//#include "mono_include_pkg.h"
//
//// Includes for EngineAPI.Component
//#include "Engine/Component.h"
//#include "Engine/GameObject.h"
//
//
//MonoObject* EngineAPI_Component_GLUE_GEN::Get_GO_Internal(MonoObject* _self)
//{
//	// Try to get native object
//	MonoObject* native_object = Engine::Mono::GetNative<Engine::Mono::Component*>(_self);
//	// Native Method: Name = GetGameObject
//	// Static Accessor: Name = ComponentManager, Type = DoubleColon
//	return Engine::Mono::NativeToMono(ComponentManager::GetGameObject(native_object));
//}
//
//void EngineAPI_Component_GLUE_GEN::Bind()
//{
//	// Binding for EngineAPI.Component
//	mono_add_internal_call("EngineAPI.Component::Get_GO_Internal", (void*)Get_GO_Internal);
//
//}
//
