// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: EngineAPI.dll
// Type: EngineAPI.NativeObject
// Generated on: 2025-09-09 09:57:21

// Includes for the header
#include "EngineAPI_NativeObject_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for EngineAPI.NativeObject


void EngineAPI_NativeObject_GLUE_GEN::Bind()
{
	// Binding for EngineAPI.NativeObject

}

