//// This file is generated by CSBridge.
//// Do not edit this file directly.
//// Generated from: EngineAPI.dll
//// Type: EngineAPI.Class1
//// Generated on: 2025-09-09 15:01:46
//
//// Includes for the header
//#include "EngineAPI_Class1_GLUE_GEN.hpp"
//
//// Mono package include
//#include "mono_include_pkg.h"
//
//// Includes for EngineAPI.Class1
//#include "Runtime/Engine/Public/EngineAPI/Class1.h"
//
//
//int32_t EngineAPI_Class1_GLUE_GEN::Add(int32_t a, int32_t b)
//{
//	// Static Accessor: Name = Class1CPP, Type = DoubleColon
//	// Native Method: Name = Adder
//	return 	Class1CPP::Adder(a, b);
//}
//
//void EngineAPI_Class1_GLUE_GEN::Bind()
//{
//	// Binding for EngineAPI.Class1
//	mono_add_internal_call("EngineAPI.Class1::Add", (void*)Add);
//
//}
//
