// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: EngineAPI.dll
// Type: EngineAPI.Class1
// Generated on: 2025-09-09 15:01:46

#ifndef EngineAPI_Class1_GLUE_GEN_HPP
#define EngineAPI_Class1_GLUE_GEN_HPP

// Includes for mono API
#include "mono_include_fwd.h"

// Includes for EngineAPI.Class1
#include "Runtime/Engine/Public/EngineAPI/Class1.h"

// Object: EngineAPI_Class1_GLUE_GEN
class EngineAPI_Class1_GLUE_GEN {
// Methods for EngineAPI.Class1
	static int32_t Add(int32_t a, int32_t b)

	// Bindings for EngineAPI.Class1
	public:
		static void Bind();

};

#endif // EngineAPI_Class1_GLUE_GEN_HPP

