// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: EngineAPI.dll
// Type: EngineAPI.NativeObject
// Generated on: 2025-09-09 11:04:39

#ifndef EngineAPI_NativeObject_GLUE_GEN_HPP
#define EngineAPI_NativeObject_GLUE_GEN_HPP

// Object: EngineAPI_NativeObject_GLUE_GEN
class EngineAPI_NativeObject_GLUE_GEN {
	// Bindings for EngineAPI.NativeObject
	public:
		static void Bind();

};

#endif // EngineAPI_NativeObject_GLUE_GEN_HPP

