// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: EngineAPI.dll
// Type: Microsoft.CodeAnalysis.EmbeddedAttribute
// Generated on: 2025-09-09 00:02:00

#ifndef Microsoft_CodeAnalysis_EmbeddedAttribute_GLUE_GEN_HPP
#define Microsoft_CodeAnalysis_EmbeddedAttribute_GLUE_GEN_HPP

// Object: Microsoft_CodeAnalysis_EmbeddedAttribute_GLUE_GEN
class Microsoft_CodeAnalysis_EmbeddedAttribute_GLUE_GEN {
	// Bindings for Microsoft.CodeAnalysis.EmbeddedAttribute
	public:
		static void Bind();

};

#endif // Microsoft_CodeAnalysis_EmbeddedAttribute_GLUE_GEN_HPP

