// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: EngineAPI.dll
// Type: Microsoft.CodeAnalysis.EmbeddedAttribute
// Generated on: 2025-09-09 09:57:21

// Includes for the header
#include "Microsoft_CodeAnalysis_EmbeddedAttribute_GLUE_GEN.hpp"

// Mono package include
#include "mono_include_pkg.h"

// Includes for Microsoft.CodeAnalysis.EmbeddedAttribute


void Microsoft_CodeAnalysis_EmbeddedAttribute_GLUE_GEN::Bind()
{
	// Binding for Microsoft.CodeAnalysis.EmbeddedAttribute

}

