// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: EngineAPI.dll
// Type: System.Runtime.CompilerServices.NullableAttribute
// Generated on: 2025-09-09 09:57:21

#ifndef System_Runtime_CompilerServices_NullableAttribute_GLUE_GEN_HPP
#define System_Runtime_CompilerServices_NullableAttribute_GLUE_GEN_HPP

// Object: System_Runtime_CompilerServices_NullableAttribute_GLUE_GEN
class System_Runtime_CompilerServices_NullableAttribute_GLUE_GEN {
	// Bindings for System.Runtime.CompilerServices.NullableAttribute
	public:
		static void Bind();

};

#endif // System_Runtime_CompilerServices_NullableAttribute_GLUE_GEN_HPP

