// This file is generated by CSBridge.
// Do not edit this file directly.
// Generated from: EngineAPI.dll
// Type: System.Runtime.CompilerServices.RefSafetyRulesAttribute
// Generated on: 2025-09-09 00:02:00

#ifndef System_Runtime_CompilerServices_RefSafetyRulesAttribute_GLUE_GEN_HPP
#define System_Runtime_CompilerServices_RefSafetyRulesAttribute_GLUE_GEN_HPP

// Object: System_Runtime_CompilerServices_RefSafetyRulesAttribute_GLUE_GEN
class System_Runtime_CompilerServices_RefSafetyRulesAttribute_GLUE_GEN {
	// Bindings for System.Runtime.CompilerServices.RefSafetyRulesAttribute
	public:
		static void Bind();

};

#endif // System_Runtime_CompilerServices_RefSafetyRulesAttribute_GLUE_GEN_HPP

